### ISSUE TITLE
Filter Loaded

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#10]
Sometimes I only want to concentrate myself on the active tabs. It would be great to have a filtering option to show only tabs that are loaded without the unloaded tabs.

**Comment by madprops** [comment]
Ok, makes sense.

**Comment by madprops** [comment]
Version `986` now has a `Loaded` filter on `Tabs` mode. A new command `Filter Loaded` was also added.

**Comment by N3C2L** [comment]
Wonderful. Thank you!
