### ISSUE TITLE
Reverse Sorting only for Selected Tabs possible? 

### ISSUE THREAD

**Issue by eLionsson** [madprops/grasshopper#100]
Hello madprops.

I have been using your Grasshopper for a long time and am very impressed with the many options this add-on offers. Now I have a request: was it possible to implant a function that reverses the sorting of order of marked tabs?  This currently doesn't seem possible to me, or am I perhaps overlooking this?

CU Lionsson

**Comment by madprops** [comment]
I don't know what you mean by marked  tab.

**Comment by eLionsson** [comment]
Wow: what a fast answer! Thank you very much for that. I will try to describe:

There are e.g. 20 open tabs. I open the Grasshopper sidebar. Then I mark the last 5 tabs in the sidebar. Perhaps „I select“ is the correct expression, sorry my perhaps wrong wording. I then want to reverse the order of those 5 tabs. For example by a right klick > sort > reverse order.
They currently show up in the order of having been opened.

Hope this is more understandable…
CU Lionsson

**Comment by madprops** [comment]
Ah I see. I'd have to add a Reverse command. I'll see if it's doable. But I can see it being useful.

**Comment by eLionsson** [comment]
And again: thank you very much. I'm very much charged with tension to see whether you will be able to manage this. This function would make my work with Firefox much easier. CU Lionsson

**Comment by madprops** [comment]
### Added Reverse, Sort Asc, and Sort Desc

Added these to the item menu:

![reversemenu](https://github.com/madprops/grasshopper/assets/206498/570ac336-78cc-4535-8d59-2a89278cfd35)

(These are only visible when multiple items are selected)

Added a permission to enable/disable the confirm dialog:

![warn234](https://github.com/madprops/grasshopper/assets/206498/f2f16889-4d23-4029-a6f8-9f8bbb44c382)

**Comment by eLionsson** [comment]
That simply works. I Don#t know what to say. I am very impressed. Thank you very very much. Mille grazie. CU Lionsson

**Comment by eLionsson** [comment]
I will check in my every-day-work the next time, and if there are any complications I will let you know. What I already tried: closing and opening both the window in question, and the entire Firefox. The reversed order stays. Great! CU Lionsson
