### ISSUE TITLE
[BUG] Click on an item doesn't open a page anymore!

### ISSUE THREAD

**Issue by user0022** [madprops/grasshopper#101]
Hello!
Critical issue...

After update, I see that, a click on an unloaded tab in the sidebar gives no reaction, one stays in the same web page.
Firefox tab bar keeps working, and I see that once I have opened/loaded a tab from FF tab bar, GH can focus them when I click on them, but still the same for unmloaded ones.

I just tried clicking in the popup view, or disabling/enabling GH, or restarting Firefox, but no change.

**Comment by user0022** [comment]
-> But I did a double-click on an unloaded tab, and then it worked.

**Comment by madprops** [comment]
Yes. It's a new thing. I guess I should disable it by default. I didn't like opening unloaded tabs by accident. The setting is `Load Lock` in general.

**Comment by madprops** [comment]
It should work as before now.
