### ISSUE TITLE
Sticky filter search bug in combination with auto restore

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#103]
Please activate these settings:

1. filter > sticky filter > activate

2. general > auto restore > on action

3. do a tab search > problem: displaying only 1 letter then it deletes 1 letter afterwards

4. another bug with sticky filter activated: set auto restore to "never" or any other auto restore activation option by seconds (1-30).

5. search at least 5 different tab names > problem: often tabs will be auto activated only by typing letters in the search bar (mostly after typing 4-5 letter of the tabs name)

**Comment by madprops** [comment]
@N3C2L can you remind me what sticky filters do? I don't use it and I don't remember exactly what it was supposed to solve.

**Comment by madprops** [comment]
I have removed the sticky filter code. It was causing several problems and complicating things.

**Comment by N3C2L** [comment]
Yeah, sorry for late reply I was away after posting this issue. we discussed it here:
https://github.com/madprops/grasshopper/discussions/51#discussioncomment-7663959
It would be cool if you can fix it instead of removing it.

**Comment by madprops** [comment]
Alright I uploaded some fixes regarding auto-restore and sticky filters. Let me know if things work properly now.

**Comment by madprops** [comment]
Uploaded again. The most recent version is v2812

**Comment by N3C2L** [comment]
Thanks! Search is fine now with sticky filters activated!

However I think something else is now going on when auto-restore is "on action":

You can't trigger a double click action with the mouse anymore: it's flashing when double clicking an item: for example try it with "edit title" as a command for double click.

**Comment by madprops** [comment]
On Action should work now.

And Pins now get visible on text filter or on Pins filter mode.

**Comment by N3C2L** [comment]
Thanks a bunch for these fixes!  👍 I think I can close this issue.
