### ISSUE TITLE
[BUG] Tabs not opening in the right place in the sidebar view with filters.

### ISSUE THREAD

**Issue by user0022** [madprops/grasshopper#104]
Hello!
I use Firefox ESR 115, under Lubuntu 22.04 OS.

*

In sidebar view, I noticed that if I do for instance a filtering with _grass_ (for GrassHopper), and that from one of the tabs it shows after that (the tab is https://github.com/madprops/grasshopper/issues in this case), I open a link in a new tab, it sometimes opens placed a few tabs above (maybe could also be below) in the list, instead of being in the immediate following (so then below) tab.
Yet in the Firefox tab bar, I see that it opens where it is supposed to (right after the tab which it comes from).
If I erase _grass_, to be back in an list with no filter, tabs open again in the right place.

Maybe difficult to reproduce because it seems like it only happens on some tabs, of which I don't know why they have this problem and others not.

I tried the same from the same tab but with another fitlering, **Filter Loaded**, which I put as a button in Favorites panel, and the problem didn't show with the tab that sent links above.
But continuing in this filter, I opened another tab (https://github.com/madprops/grasshopper/discussions), and from it I opened https://github.com/madprops/grasshopper/discussions/83, and again, in GH sidebar it opened it right above instead of below (but still in the correct place in FF tab bar).

**Comment by madprops** [comment]
I think the issue is that since you are filtering the tabs, it will not show the actual real order, since it's filtering out some items. And when you remove the filter it looks as it should. That's what I think it's happening.

**Comment by user0022** [comment]
Thank you yes it could be, but in fact in this case I don't think!
Because I guess that the only thing that can happen when a filter is applied (if everything works properly), would be this:
>With no filter: from tab A, a new tab C can open after tab B (if I have already opened tab B from tab A before opening C), and I see all A B C tabs, B below A, C below B.
>With a filter that makes disappear tab B (e.g. because its title doesn't match with the filter), there is still tab A, and tab B below tab A.
But what I see, is that when I open a tab C (or even a tab B), it sometimes opens above tab A, with 2 or 3 unloaded tabs between them, and so that is not normal isn't it?

*

I also saw a bit more about this behavior, in sidebar I had filtered tabs with a word in [Filter] field, and there I had closed 3 tabs, and reopened them, and like before they didn't show up in their right previous place. But simply by closing/reopening the sidebar, they showed in their right place.

**Comment by madprops** [comment]
Sounds like there might be a bug then. But I'd need a step by step example of how to test  this. You say this doesn't happen all the time so that's harder. If you find a way to make the error happen that would be good. I did make a quick test opening tabs while on Loaded filter. They seem to be open normally.

**Comment by user0022** [comment]
OK, so I think I found a case when it happens every time. Maybe some things are useless excuse me but I didn't test to remove all things to see if one is useless...
It is the previous example I mentionned, but with details.
1/ Have among other tabs 3 following tabs (following is maybe important, at least it is easier to see) with same word in title (e.g. 3 issues pages of GrassHopper repository).
2/ In sidebar, type grass in [Filter] field.
3/ Close tabs one by one from the left to the right in Firefox original tab bar (closing them from sidebar maybe doesn't make the problem appear).
4/ Reopen them one by one with Ctrl+Shift+T shortcut.
Normaly, for me they always will show up in a wrong place, 2 or 3 unloaded tabs above their original place.

**Comment by madprops** [comment]
https://github.com/madprops/grasshopper/assets/206498/9770c032-ffa0-43da-ad48-0319dbe47bf8

Seems to work fine. Not sure if I'm missing something.

**Comment by user0022** [comment]
In video, visibly you forgot to type grass!

**Comment by madprops** [comment]
Oh yeah sorry. Here's with the text filter:


https://github.com/madprops/grasshopper/assets/206498/9b3f2c7d-b630-4843-b62c-221f20f3e4bd

**Comment by user0022** [comment]
Ah yes there is grass, but now I see I had forgotten a detail, the 3 tabs must also be among other tabs (e.g. 5 above and 5 below) with grass in their title (so GH issue pages too), because of course otherwise we can't see that they don't reopen in a wrong place as the right or wrong place is seen in comparison to other ones... Her in the 2nd video as they are alone the have no comparison place...

**Comment by madprops** [comment]
https://github.com/madprops/grasshopper/assets/206498/85762da3-d779-44b5-8dc3-8d2433f0c070


https://github.com/madprops/grasshopper/assets/206498/8ebe6458-f149-4ccb-9409-fbde727ab977


Seems to work fine here.

**Comment by user0022** [comment]
Aaaah yes this time the problem should have appeared...
I try to see 2 or 3 things, maybe it is because I have tabs unloaded, or tabs with a color, or sth else (addon, being ESR...), I'm a not as fast as you but I'm on it, I come back when checked all I have imagined...

**Comment by user0022** [comment]
It's been a bit long but I finally found I think.
I first tried all I imagined in ESR and nothing worked:
-Without unloaded tab.
-Removing colors from tabs.
-Disabling all other addons (but then staying offline for being online without uBlock Origin is fearful).
-Purging history+cookies+...
-Disable/enable GH.
-Restarting FF.
-Moving back sidebar on the left (as I had put it on the right).

Then I tried on FF 126 (classic but in Snap version), as I was with FF 115 (ESR) for the moment.
I saw there was no problem here, so as GH had yet no modification I gave it 1 by 1 or 2 by 2 the same settings than in ESR, and after each modification I checked if the problem had appeared.
And in the end it worked, it is the Tab Box, the one you had told me [here](https://github.com/madprops/grasshopper/issues/96)I could use to display pinned tabs more like in Firefox tab bar.
Installing it created the problem, and toggling it in "hidden" makes the problem disappear (still with the same things, filtering with text, etc).
I had done:
Settings > Tab Box.
-Tab Box Position: Bottom to Top
-Tab Box Size: Normal to Small.
-Tab Box Mode: Recent to Pins
-And in the bottom of the main view, Toggle Tab Box to display it.
If you do this this time it is almost sure to appear (but maybe it comes with this setting, but in combination with another I have also done who knows!).

And then confirmed in FF ESR 115 that the problem disappeared when I toggled Tab Box in "hidden".
(For the fix by hiding to be taken into account, for example Tab Box must be hidden and then the sidebar closed/reopened with Ctrl+Shift+Space shortcut.)

*

A small remark: I had forgotten, but I had changed a setting to leave the text filter in its field when I click on a tab, as by default it is deleted.
This setting being: General > Auto-Restore: [On Action] changed to [Never]
Fortunately you had done it too, otherwise it would have been more complicated to make the same tests (or you had understood that I had done it and you put the same setting for the moment of the test).
(A setting that maybe could be on [Never] by default but I'm not sure!)

**Comment by madprops** [comment]
Ah interesting. Maybe the tab box is causing something to misbehave. Though I did a quick test doing the steps but with the Tab Box open, it seemed to work fine.

**Comment by user0022** [comment]
I think I found when it happens (once more, maybe for good this time!).

So in FF 126, I reset everything but:
-Auto-Restore: [On Action] to [Never]
-And the Tab Box.
And the problem still appeared, but trying in another window it did not.
The difference between the 2 windows is that in the first one the Tab Box contains pinned tabs, and in the second one, the Tab Box is empty. So I think your Tab Box was empty too, and if you fill it with pinned tabs (and with of course also filtering with text, etc) the bug will appear.

I can also give you the console output, but it is long and is maybe finanally useless.
