### ISSUE TITLE
Previous tab indicators on listed tab items

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#11]
Some thoughts for this request:

Placed before(?) the favicon of the tab item.
First previous tab indicator with a single colored thing (left colored border?).
All other previous tabs (e.g. 2-10) with the same colored left border (other color than first prev. tab).

Something in that direction would be awesome to better distinguish between last used tabs and older tabs.

**Comment by madprops** [comment]
1) Are you aware of Recent Tabs when you right click the Step Back button (near top right) ?

2) I'm not sure what you mean by previous tabs, you mean the previous/recent used tabs?

So add an indicator to fresh tabs to quickly get back to them is what I'm understanding.

**Comment by madprops** [comment]
I think I understand what you mean, like leaving a trace of activity. I think it's interesting, I'll try it out.

**Comment by madprops** [comment]
![asdf234](https://github.com/madprops/grasshopper/assets/206498/2f42c3ca-bfa2-4081-a524-858d49ecf611)

I'm trying this. I think it might work better with fewer items like 3 or 5, but that can be a setting. Also not sure how I could use different colors for that (since themes can be customized). Then there's the question if I reserve the space for the border or if I let items move a little when activated.

**Comment by madprops** [comment]
I'll continue this tomorrow, feel free to leave messages.

**Comment by madprops** [comment]
After using indicators for a bit I think it looks confusing, too much feedback, and the order is not clear. Plus it complicates the item structure. I'm gonna decide for now to not implement it. Maybe knowing about Recent Tabs is enough to jump back to tabs.

**Comment by N3C2L** [comment]
Sorry for the late reply but my dad celebrated his birthday yesterday.
I am sorry that I did not express my request more clearly, english is not my native language. Thanks for your testing and feedback. I was not aware, that this would lead to confusion in the tab item structure. But I would be glad if you could test this tab indicator with numbers (counter) instead. This counter begins with 1 for the first previous tab, 2 for the second previous tab and so on. Counter numbers can be a setting for how many visible tabs in the list should get a number. These numbers would be easier for light and dark themes to implement. And maybe the numbers can be placed somewhere where they do not complicate the tab structure?

**Comment by madprops** [comment]
Funnily I did test it with numbers as well. From 1 to 9. Didn't find it great myself, was confusing. I might do some more tests, and probably add it as an option you can enable. I'll let you know.

**Comment by madprops** [comment]
@N3C2L ^

**Comment by N3C2L** [comment]
Ok, thanks. Maybe another idea to mix actual tabs and previous tabs: Option to put the previous tabs window below the actual tab item list. But you can navigate and click in the actual tab list above, as well as below in the previous tab list. The previous tab list below gets updated every time I click a tab in the actual tab list above. The previous tab list should be shrinked to 3-5 tabs max?

**Comment by madprops** [comment]
I implemented both. Will upload soon.

**Comment by N3C2L** [comment]
Thank you so much!
I know that I have requested many things lately. 
Please let me know if I can post another feature request that I have in my mind.

**Comment by madprops** [comment]
Yeah go ahead.

**Comment by madprops** [comment]
Ok version `989` is now up. This adds `Tab Box` and `Active Trace`. You can enable these on the `Show` category of `Settings`. Tab Box adds a box at the bottom. You can define a size. It's disabled by default. Active Trace adds the numbers on recent tabs, it's disabled by default. 

I think these are good additions.

**Comment by N3C2L** [comment]
Thank you! I love these additions, and that you can change the size of the tab box is amazing.
