### ISSUE TITLE
Waypoint up and down commands

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#114]
Thanks for this new commands! But what do they do exactly ? I have this waypoints up/down command in the footer scroll wheel buttons. (thanks for that feature!)
Is this waypoint command suppose to cycle through the recent tabs? But in my case it cycles only through some random pinned tabs and the last tab in the list on the bottom.

**Comment by madprops** [comment]
Sorry for it being so cryptic. I recently added commands to go to the first pin, the last pin, the first normal, the last normal. So I thought I'd add a command that cycled through all of those in a single action. So "waypoints" are the edges of pins and normals.

Also i'll upload a new version in some minutes.

**Comment by N3C2L** [comment]
Ah, thanks for this clarification.

**Comment by madprops** [comment]
New version. Renamed Waypoints to Edge. 

Also added `Next Unread` command to go to the next unread tab.

Recently added commands to cycle between pins, and cycle between normals.

Also removed `Jump` from most jump commands, but they do the same thing.

Instead of `Jump Header Down` you'll see `Header Down` etc.

Because it's shorter.

**Comment by madprops** [comment]
Changing to to playing to Playing Up and Playing Down
Unread Up , Unread Down
All these are done with a centralized Jump function which is handy.

**Comment by N3C2L** [comment]
Very useful, thanks.
I'd appreciate also "recent up" and "recent down" for quickly go to last/prev. recent tabs. 😁

**Comment by madprops** [comment]
Hmm that's tricky. Recent Tabs uses a temporary list of the last visited tabs and travels through it until it gets exhausted. Also I don't know what 'up' or 'down' would be in this case. If 'up' means the most recent tab that is above the current tab I guess it's doable.

**Comment by madprops** [comment]
What I'm gonna do is something akin to `Next Recent` which I don't know why it doesn't exist yet

**Comment by N3C2L** [comment]
I think there are some shortcuts by sidebery plugin
Active tabs history: Back
Active tabs history: Forward
Maybe you can look in the source code there

**Comment by madprops** [comment]
Alright I'm adding that. The limitation it has a timeout that resets the used list after 2 seconds of inactivity. So you can do back and forward but if you stop using those after 2 seconds the list gets re-fetched. But I guess it's still useful. An idea could be to map it to wheel up and down on favorites empty top.

**Comment by N3C2L** [comment]
Excellent!
I also have these commands now mapped on wheel up/down in the favorites empty top space. Many thanks for these implementations!
I think I can close this issue.
