### ISSUE TITLE
Some problems with commands on unloaded tabs

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#117]
Commands on unloaded tabs with the right click menu or the hover button are working great with nearly every command. For example add tag, add icon, edit title etc.
But if I use the "New" cmd with the hover button on an unloaded tab, the new tab will be created below the active loaded tab and not below the unloaded tab.
I could click on the unloaded tab to load it, and create then the new tab below. But this is a problem when the unloaded tab is for example a youtube video or another big website which needs to load first.
Workaround would be to copy and paste the new tab below the unloaded tab. But the disadvantage of this is, that we have to copy and paste a new tab to do this.
Creating header/subheader below an unloaded tab (with the hover button) isn't working either, but creating splits below unloaded tabs are working fine.

Another bug, but that can be addressed here in this issue: If I add some urls here: Settings>General>Custom Urls, then these custom urls commands are not available for example in the hover button menu or extra menu (the right click menu) for adding. But the cmds are visible in the cmd palette. 
But why I mention this here and not in another issue: It would be important that these custom urls would also get opened below an unloaded tab if executed on an unloaded tab with the hover button or right click menu.

In firefox's about:config site, my settings are:
browser.tabs.insertAfterCurrent > true
browser.tabs.insertRelatedAfterCurrent > true

So that every new tab will be created next to the active tab by default. That's good for browsing when the active tab is loaded. But if I want to change my zone by navigating to another header, then creating new tabs below some unloaded tabs there should be possible. 

If I turn the values from the about:config site to "false", then It's not working either with new tabs opening below some unloaded tabs inside the grasshopper interface. But maybe new tabs could be created somehow (not focused) and then pasted below the unloaded tabs from where the cmds was executed? 

Or maybe the code repro from tree style tabs can help, because when you right click an unloaded tab in their interface, and click "new tab", the new tab will be created below this unloaded tab: 
https://github.com/piroor/treestyletab

**Comment by madprops** [comment]
>But if I use the "New" cmd with the hover button on an unloaded tab, the new tab will be created below the active loaded tab and not below the unloaded tab.

That is the behavior of the browser, I don't think the extension is meant to touch that.

>Creating header/subheader below an unloaded tab (with the hover button) isn't working either, but creating splits below unloaded tabs are working fine.

Not sure what you mean, but if I use the insert header or insert header commands using the hover button on the tab below  an unloaded tab, or on the unloaded tab itself, it works as expected (the tab is created above the target tab).

>these custom urls commands are not available for example in the hover button menu or extra menu (the right click menu) for adding. But the cmds are visible in the cmd palette.

I am seeing the commands in hover menu when I search for the title I gave them.

>It would be important that these custom urls would also get opened below an unloaded tab if executed on an unloaded tab with the hover button or right click menu.

Ok that's an interesting idea.

**Comment by N3C2L** [comment]
Thanks a bunch for this updates. 👍 
Your solution now with the special opening menu is my savior here. 
 I am sorry, but no matter what I tried with the settings in my browser, I couldn't get it to work before 😁.
But now, when "Below special" is activated, it's working all the time. Also with all header tabs! Thanks!
Also the custom urls are appearing now properly in the hover menu or to right click menu. By the way thanks for this great feature!
And they also opening under unloaded or active tabs all the time! Thanks! I am sorry here again, that I couldn't see the custom urls before when filtering by typing in the menus (Yes I did know this before, thanks and love this filtering methods, true time saver).

**Comment by N3C2L** [comment]
I think adding URLs in the custom Urls menu need the protocol (http or https), because if I add some urls with only the www prefix like www.youtube.com, it doesn't seem to work. Can you confirm this?

**Comment by N3C2L** [comment]
Hmm, I need to restart the browser to make the added custom urls visible in the hover button adding menu or right click menu. Can you reproduce that?

**Comment by madprops** [comment]
Yes I can confirm both of those, I fixed them, will upload soon

**Comment by madprops** [comment]
Should be fixed now. Plus there was some small bug in the menu library too

**Comment by N3C2L** [comment]
Thanks, much appreciated.
