### ISSUE TITLE
Favorite Bar

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#12]
I would find this advantegous: A horizontal favorite bar below the highest button bar. Maybe filled with 5-10(?) buttons. Sole buttons maybe reduced to 30-50 pixel so that a favicon only can be visible inside a button. In every button you can put in a command. The favicons of the already implemented commands can be used to show on a button when a button is filled with this command. The favorite bar should be visible like the top button bar even when scrolling the tab item list.

**Comment by madprops** [comment]
I see. I find the icon thing confusing. My guess is: You want to use the icon of the assigned command to fill the button. I'll consider the idea. It would require a Settings category. And I guess it would be too much to have favorite buttons per mode (tabs, history, etc), so it would be global.

**Comment by N3C2L** [comment]
Yes, you are right with the icons assigned commands to fill the buttons. And yes, the bar should be global, that would be awesome.

**Comment by madprops** [comment]
![favorites234](https://github.com/madprops/grasshopper/assets/206498/08a78c41-5c2b-4889-9ce5-5472eaa77035)

You can add `Favorites` in it's dedicated Settings category.

Will upload soon to v990.

**Comment by madprops** [comment]
The bar can look weird, especially with only 1 or 2 buttons. I'm trying it to now show it in a sort of hamburger menu. Which is almost the same except it requires 1 extra click.

**Comment by madprops** [comment]
Nvm I guess a button is more boring.

**Comment by madprops** [comment]
It should be available now.

**Comment by N3C2L** [comment]
Thank you! Love the fact that you put the "go to top" button and the colors on this favorite list.
Maybe the interface of the favorites settings could be improved: A box below which lists the actual favorite items (so that you don't need to click "list"). Below this box two arrows where you can move the commands up and down. An additional button beside these arrows which removes a command from the list.

**Comment by madprops** [comment]
Maybe later. The `addlist` component is a generic component to deal with all lists in settings. I'd have to change how it works. But I know what you mean.

**Comment by N3C2L** [comment]
Thanks. I did not know that you can reorder it this way. I'm happy with that. Maybe it would lead to less confusion for users when the button "edit" leads to that menu instead of clicking an item first.

**Comment by N3C2L** [comment]
Sorry I mean the edit menu should lead to the previous menu when clicking an item first.

**Comment by madprops** [comment]
![addlist234](https://github.com/madprops/grasshopper/assets/206498/61919b1c-67b1-420e-ac1c-1d7f4aeee77d)

Next version will make Edit act like that. And added a dedicated Data button for the old Edit and Clear.

**Comment by N3C2L** [comment]
Much appreciated.

**Comment by madprops** [comment]
Adding re-ordering for list views. The list still needs to be spawned but now it will be capable of re-ordering items on the fly.

https://github.com/madprops/grasshopper/issues/14

**Comment by N3C2L** [comment]
That's very useful. Thanks.
