### ISSUE TITLE
Bookmark filtering

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#120]
Current problem: when a new bookmark is added, and then you search for it inside grasshoppers bookmarks interface, it doesn't appear at the top of the list. So, assuming there are multiple bookmarks that have the same keywords in the bookmark, the most recently added bookmark is not displayed at the top when you search for it.
What are the priorites here inside the bookmark filtering? How the filters in bookmarks decide what's on top and what lower ranked?

**Comment by madprops** [comment]
So the issue is that 2 sets of bookmarks are fetched.

When you bookmark a url through grasshopper it is added to the `Grasshopper` directory.

When bookmarks are shown, it shows the bookmarks from that directory at the top.

And the rest of the bookmarks are shown below this set.

How do you suggest it should be displayed instead?

**Comment by N3C2L** [comment]
I don't know about that. I just meant that when actively filtering for a bookmark, this view might be changed so that the prioritization could be altered according to "date added". So that the most recently added bookmark appears at the very top, and then in descending order according to the date added.

**Comment by madprops** [comment]
I'll just remove the bookmarks directory and mix the bookmarks.

**Comment by N3C2L** [comment]
Ok. Thanks. Here a search example: Let's say I have several bookmarks containing the word "github". And then I add another bookmark with the term "github". After that, I enter "github" in the grasshopper bookmark filter list at the top, and the most recently added github URL should appear at the very top (which is not the case actually).

**Comment by N3C2L** [comment]
I understand. Thanks.

**Comment by N3C2L** [comment]
Thanks, it's working. One question: When is deep max search activated in a search?

**Comment by N3C2L** [comment]
Ah, thanks. I didn't see the command "deep mode", because I didn't filter anything before 😁 
No it's clear, thanks.

**Comment by madprops** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/search

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history/search

The raw query is limited to the apis ^

I don't think they do that. but it might be possible to process it manually after receiving results perhaps.

**Comment by madprops** [comment]
![quotes234](https://github.com/user-attachments/assets/06401abd-8390-4cdc-a5b9-7bd156cf9b22)

I'm gonna try something.

**Comment by madprops** [comment]
Quotes are going to work on next version, for all modes. 

Will also work with aliases.

**Comment by N3C2L** [comment]
YES, this is brilliant! 
So useful, because no other extension I tried or the the url bar by firefox self can do this. 
Many thanks!

**Comment by madprops** [comment]
On search modes like history and bookmarks there might be slight limitations since what it's going to do is a post-result filter, so it might not find very deep/old results.

Also I think this is most useful for when searching for title, so I'm going to automatically turn the filter into a "by title", to discard urls etc, when it sees you are using "quotes". Not sure if that is a good idea.

**Comment by madprops** [comment]
Ok `v3072` is up

As a side effect, a single quote acts as a "start" boundary:

For instance: `"tar` will only match things starting with that like `tarpit`  while "tar" would only match that exact word.

**Comment by N3C2L** [comment]
Great, thanks! The single quote is also a nice addition!
I have now F1 assigned to tab search (grasshopper popup). F2 assigned to history search (macro that opens the grasshopper popup and then switches to the history mode). F3 assigned to bookmark search. (macro that opens the grasshopper popup and then switches to the bookmarks mode).
And I have in about:config > browser.bookmarks.openInTabClosesMenu > false
This setting is also working for the grasshopper popup: When you are opening a bookmark with the middle mouse click, the menu will stay open. Good if you want to open multiple bookmarks at once. This setting from above works in the native firefox bookmark bar too, where a middle click on a bookmark won't close the menu.
Maybe a bug I found: If I execute the grasshopper popup cmd from inside the grasshopper sidebar, it seems it's not working. Can you confirm that?

**Comment by madprops** [comment]
>I have now F1 assigned to tab search (grasshopper popup). F2 assigned to history search (macro that opens the grasshopper popup and then switches to the history mode). F3 assigned to bookmark search. (macro that opens the grasshopper popup and then switches to the bookmarks mode).

That's interesting. Is that a firefox macro or a system macro?

>And I have in about:config > browser.bookmarks.openInTabClosesMenu > false
This setting is also working for the grasshopper popup: When you are opening a bookmark with the middle mouse click, the menu will stay open. Good if you want to open multiple bookmarks at once. This setting from above works in the native firefox bookmark bar too, where a middle click on a bookmark won't close the menu.

Yeah, not sure if you're saying something could be improved though

**Comment by N3C2L** [comment]
> 
> That's interesting. Is that a browser macro or a system macro?
> 

The macros are very simple AutoHotkey scripts, where one key is pressed, then there's a delay, then another key. But AHK (AutoHotkey) is officially only available for Windows, I believe. However, there's also a repo that runs on Linux, but I haven't tested it because I'm on Windows: https://github.com/phil294/AHK_X11

> This made me wonder if I can launch popups/sidebars with arguments to launch with different modes.
> 

I don't know how, but sidebery can access the sidebar without needing to be in that sidebar (for example, while browsing the website). For instance, they have it here under about:addons > manage extension shortcuts

<img width="175" alt="settings" src="https://github.com/user-attachments/assets/ce6cbe5e-1a3a-450b-a975-c13678834067">

and they have lots of shortcut here, for example 

<img width="493" alt="shortcut" src="https://github.com/user-attachments/assets/d61c5366-2b58-42df-b6ff-9cd6e26c2d32">

But for popups I haven't found something.

> > And I have in about:config > browser.bookmarks.openInTabClosesMenu > false
> > This setting is also working for the grasshopper popup: When you are opening a bookmark with the middle mouse click, the menu will stay open. Good if you want to open multiple bookmarks at once. This setting from above works in the native firefox bookmark bar too, where a middle click on a bookmark won't close the menu.
> 
> Yeah, not sure if you're saying something could be improved though

I just wanted to mention how I use it, but since everything is working, I currently don't have any ideas on how something could be improved at this point. 👍

**Comment by madprops** [comment]
Autohotkey yeah, I used that in the past. 

>sidebery can access the sidebar

I'll look into it. Asking something in stackoverflow.

I'd at least register 4 new commands that can be mapped to shortcuts for each mode.

**Comment by N3C2L** [comment]
The shortcuts in the tree style plugin can also access the sidebar, maybe this is helpful:
https://github.com/piroor/treestyletab

**Comment by madprops** [comment]
Thanks. Next version will have these:

![initmodes234](https://github.com/user-attachments/assets/27f8f5b9-6cdf-451b-813e-75f9aa86b2df)

**Comment by N3C2L** [comment]
Therse are helpful shortcuts I think other users will love them aswell, thanks for implementing. 
I think I can close this as completed.

**Comment by N3C2L** [comment]
I know that when it comes to bookmarks, you want to be as careful as possible and not offer deletion and moving of bookmarks, which I also understand, because bookmark loss would be bad. 

But at the same time, you said in your description of your addon in the Firefox store that you are offering adding bookmarks, and I thank you for that. 

But currently, there is no Firefox addon that offers the following bookmarking option: 1. select multiple tabs 2. bookmark items 3. here a popup menu similar to that the command palette could now open, where you only see folders. and whichever folder you select here, the selected tabs will be saved there. 

That would be great, because all Firefox addons and also the native bookmarking function of Firefox itself do not offer filtering directly to the folder via keyboard during the bookmarking process. We have to struggle through folder lists with the mouse everywhere, which is really annoying. 

Therefore, I would be grateful if you could offer the feature from above in your addon.

**Comment by N3C2L** [comment]
Hmm, after some research, there are some addons that can do this, but sadly it doesn't work when I have tabs selected inside the grasshopper interface. And I have hidden the native ff tabs on top.
https://github.com/boiwantlearncode/multiple-bookmarker
Another one, but sadly not on github and works only with one tab selected:
https://addons.mozilla.org/en-US/firefox/addon/quick_bookmark_to_folder/

**Comment by madprops** [comment]
Hmm so when bookmarking, show the list of existing bookmark folders, pick one,  bookmark all selected tab on that folder? Sounds like it can be done

**Comment by N3C2L** [comment]
> Hmm so when bookmarking, show the list of existing bookmark folders, pick one, bookmark all selected tab on that folder? 

Yes! That would be great!

> Should that be default behavior? 

Idk, but it would be very helpful for me or other users.

> Under a setting? Under a different command?

Hmm, could be useful to introduce different cmds if someone have a fixed favourite folder (like it is now) or want the new popup where someone wants to choose a folder.

**Comment by madprops** [comment]
And if tabs are already bookmarked somewhere, bookmark on that folder anyway? If they're already in that folder then ignore?

**Comment by N3C2L** [comment]
> And if tabs are already bookmarked somewhere, bookmark on that folder anyway? 

I do think that the bookmark should still be created in this folder. Although there would then be a duplicate, everyone can decide for themselves whether they want to have the duplicate in another folder. Personally I like to have duplicates in other folders, because I can then open them also if I I need them too.

> If they're already in that folder then ignore?

An ignore function would certainly be interesting! But perhaps the user would then need a message that something wasn't bookmarked because it already existed.

**Comment by madprops** [comment]
Ok next version will have this.

The new command is `Bookmark Folder`.

Also new command: `Select Bookmarks`

This will set the current bookmarks folder to display in Bookmarks mode.

For instance if you want to see bookmarks of "trees" or bookmarks of "cars".

**Comment by N3C2L** [comment]
> Ok next version will have this.
> 
> The new command is `Bookmark Folder`.

Amazing, thanks!

> 
> Also new command: `Select Bookmarks`
> 

Wow, I will use that for sure! Thanks!

**Comment by N3C2L** [comment]
I'll be offline for the next few hours due to zZzzZz, but if I may suggest a small improvement: I have over a thousand folders (probably collected from almost 20 years of Firefox usage 😁), and I already notice a delay when calling up the folder list. Would it be possible to limit this folder list to about 100 folders on the first call? For both commands. That would be great. Because for me personally, it's not necessary to see so many folders at once, as I usually type in a specific folder using the keyboard and then save it.

**Comment by madprops** [comment]
Damn that's a lot of bookmarks, I hear ya, so here's this:

First of all a setting to limit the max folders for pickers, default at 25:

![maxbkmr](https://github.com/user-attachments/assets/10024366-aaf4-42b8-8666-f215e738a7fe)

But also a new command to search. Like select but you first input a search string.

![searh34](https://github.com/user-attachments/assets/dc7d0ad3-116a-4387-9475-f3ca15395149)

Also, when bookmarking, you can search first instead of picking from list, alternative to Bookmark Folder. I just added a 2.

![bkm324](https://github.com/user-attachments/assets/ac5d1dc6-36b6-4002-bded-cd6422bc46f7)

**Comment by N3C2L** [comment]
Thank you for these settings! 

However, I've noticed that the delay (2 seconds delay between command execution and spawning of the list) is the same whether I enter 100 or 9999 in "Settings > More > Max Bookmark Folders". 

But your other function to limit bookmarks works at this point:
Settings > Filter > Max search items: 100
 
This means that when I enter 100 here, everything in the item list is instantly available. Consequently, when I perform a Deep Search (20,000 items), it takes about 3 seconds for the item list to load, which is probably normal because I have this bookmarks:

<img width="232" alt="settings aafn plugin" src="https://github.com/user-attachments/assets/70e4d50e-d322-443d-a266-653ab9f2dd12">

This statistic comes from this plugin, which can be viewed in the settings of this plugin: https://github.com/aaFn/Bookmark-search-plus-2
This addon has a setting that might be interesting
<img width="466" alt="settings aafn plugin 2" src="https://github.com/user-attachments/assets/6fcd3f9f-0f46-4a48-83e7-c7766205ebd1">

Another remark about the "Max Bookmark Folders" setting mentioned above: If this setting is set to a value below the actual number of folders (e.g., I have 1175 folders and the value is set to 100), then in the spawned folder list, the folders are no longer listed according to last used. This means that if I set the value to 1175 or higher + then I bookmark a page in a folder, that folder will then be displayed at the very top of the spawned folder list, which I find great and very practical. Can the most recently bookmarked folder always be displayed at the very top for all folder filtering or folder selection? That would be fantastic.

**Comment by madprops** [comment]
Ah right. I guess it fetches everything in 

`let nodes = await browser.bookmarks.getTree()`

Not sure how to make that faster or pre-sort it

**Comment by N3C2L** [comment]
Thank you for the improvements. While I can't help precisely here, it would be great if you could examine the addon I mentioned above for the following: When you open your bookmarks with this addon in a new tab (right-click on the BSP2 icon > Open BSP2 in a new Tab), all bookmarks are instantly displayed quickly there. Perhaps it helps how to make it faster.

**Comment by madprops** [comment]
Yeah checking that extension seems to be the only way.

I got this response from the previous solution:

`As you can see in devtools performance profiler, getTree reads the entire tree, which is the slow part. Your traverse doesn't take any noticeable time at all. There's no API to do what you want.`

**Comment by N3C2L** [comment]
I see. Thanks for checking.
Although sidebery also offers a search function for bookmarks, it is slower than BSP2 when accessing bookmarks for the first time.

**Comment by madprops** [comment]
I'm gonna experiment to see if I can create a simple cache that listens to bookmarks events for reloading, in the background script.

**Comment by N3C2L** [comment]
Nice, thanks.

**Comment by N3C2L** [comment]
I'm off due to zZzzzZz, but I hope you have a good start in the day and things are going well with the cache script 👍 

Idk if it's helpful for you but in the big changelog from the BSP2 plugin there is this interesting thing written:

2.0.27 07/07/2018: Bugs & improvements
Implemented optimization of loading the bookmark tree from local store where the add-on keeps it up to date, instead of from FF API each time. This should be the second major improvement for users with many bookmarks, after the display acceleration in 2.0.26. On my system, this is dividing by two the initial time before the tree is available when starting FF, and dividing by 4 when switching off and on the sidebar with the Action button in the toolbar (or with the shortcut key). Gains should be much bigger with high number of bookmarks. https://github.com/aaFn/Bookmark-search-plus-2/issues/5 This is roughly making no difference when the add-on is first installed, since on install we have to read the FF API to get the initial bunch of bookmarks.
Added an option to revert to old behavior of loading the bookmark tree from FF API at each load.
Added a button on the options page to force FF API tree reload (disabled when in old behavior).

You can see and search the changelog here, maybe it can be helpful:
https://github.com/aaFn/Bookmark-search-plus-2/wiki

**Comment by madprops** [comment]
Ok I think I'm done with it. Made a bookmarks server that gets updated on bookmark modifications. And when it is refreshed it is sent to a running applications so they can store their own cache of it. 

Had to cover several edge cases to work with permission granting and avoid disastrous loops. So maybe something broke badly, we'll see.

The first time you run it it might be a bit slow but subsequent calls should be faster, you tell me.

Also added a `Create Bookmarks Folder` command.

And other modifications.

**Comment by N3C2L** [comment]
Thank you so much for the bookmark server and the create bookmarks folder command. I wil update my GH asap. You said that maybe something broke badly. Where should I look for bugs or what do you think could have happen badly anywhere in GH?

**Comment by madprops** [comment]
I'm uploading some fixes soon so wait a bit.

Bugs might have arised due to the bookmarks server. Bookmarks might not show in some cases, or infinite loops when updating them. But if bookmarks get displayed normally then it should be fine.

**Comment by N3C2L** [comment]
Ok, thanks. I will wait.

**Comment by madprops** [comment]
Ok you can give it a try now

**Comment by N3C2L** [comment]
Installed it on another firefox profile just in case whitout bookmarks just for testing. Exported my GH settings and imported it in the new ff profile. One bug I discovered, but maybe related to the export settings and not to the newest bookmark server update was, that the menus where empty. For example the favorites bar / hover button have the symbols in it, but in the GH settings the list is empty. Are the menu lists in your GH listing all cmds normally since this update or is it maybe an export / import settings bug?

**Comment by madprops** [comment]
Can confirm, i'll look into it

**Comment by madprops** [comment]
It was a bug that affected all the list widgets which meant they couldn't read the data. Fixed in next update.

**Comment by N3C2L** [comment]
Thanks for this fix! It's working!

Back to the bookmark server update: I can confirm it's extremly fast now. All my over 1000 folders spawning instantly on every folder cmd, and every Deep search with over 20 000 items is spawning instantly also! Perfect! It's also faster than BSP2! 😁 

Just a small enhancement I have in my mind for the folder creation cmd. Do you think it's possible that after the folder creation cmd is run, all folders will spawn, and the picked folder there will be the parent folder in which the newly created folder will be a subfolder? That would be fine.

**Comment by madprops** [comment]
Damn, good results, nice to hear.

>Do you think it's possible that after the folder creation cmd is run, all folders will spawn, and the picked folder there will be the parent folder in which the newly created folder will be a subfolder?

Ah yeah, should be like that

**Comment by N3C2L** [comment]
An Idea for automatic execution of Deep Search: When the user begins typing, a delay is queried, similar to the setting in Filter > "Filter Delay" (Search). For example, I could imagine that after 250ms, an automatic Deep Search Filter is executed. Perhaps a delay value in ms to adjust, like the other Filter Delay (search). The advantage would be that you wouldn't always have to trigger the deep search cmd, but it would happen automatically, which would be very practical.

**Comment by madprops** [comment]
But 250ms after "github" a search is triggered, so it sounds like you want to replace "search" with deep search, so I'm confused

**Comment by N3C2L** [comment]
Oh right, hm. I think the deep search should be always performed maybe instead of the search when a user wants to activate a setting like this. Since your new implementation of the bookmark server the search is soo fast, I would prefer that over the normal search.

**Comment by madprops** [comment]
I'm gonna add those settings, then you simply adjust the items you want.

**Comment by N3C2L** [comment]
I tried increasing Max Search Items to 20 000, but then the show bookmark cmd takes longer to load. Would be great if it can 100 items on load and on search extended to 20 000

**Comment by madprops** [comment]
Hmm. I'll add a setting to auto enable deep search when a text query is used

**Comment by N3C2L** [comment]
Perfect! Thanks!

**Comment by madprops** [comment]
Next version will have these new settings

![maxwerh](https://github.com/user-attachments/assets/3f25f9a5-1ab5-41e6-9cbe-04753246a686)

And

![autodeep](https://github.com/user-attachments/assets/7a10aea6-a04e-4a27-a475-f6b4b342fe89)

**Comment by N3C2L** [comment]
Thanks for these wonderful cmds, the auto deep cmds are superb. I activated them right away.

Noticed another bug related to a bookmark folder cmd: 

Steps:
1. Run the "bookmark selection" cmd
2. Choose a folder
3. Result: The bookmarks that will now be visible in the item list do not show all the bookmarks that are actually present in this folder. It only displays the bookmarks that are set within the value under settings>filter> "max bookmarks (searches)". For example, if I enter 99999 in "max bookmarks (searches)", all the bookmarks that are actually in the selected folder are listed in the item list, but not when this value is set to 100. Maybe this has something to do with the last deep search update, because a deep search should also be performed with the command "bookmark selection".
A small suggestion regarding the name "bookmark selection": it could be confusing if people think they can bookmark a selection of tabs with this command. Perhaps the term "folder peek" would be more suitable for this command?

**Comment by madprops** [comment]
It's `Select Bookmarks`. The auto deep only kicks when there's a query.

**Comment by N3C2L** [comment]
Ok, I forgot to add one step above to reproduce it: You need to check "Auto Deep Bookmarks". And if you do that, do you see all bookmarks in every folder with the Select Bookmarks cmd?

**Comment by madprops** [comment]
I don't think select bookmarks should trigger a deep search. It just changes the current bookmarks folder. You can then type to query or manually do deep search.

**Comment by N3C2L** [comment]
I don't mean the popup with the folders. If you click a folder and after this popup in the item list, do you see the bookmarked items without the folders?

**Comment by N3C2L** [comment]
After I clicked a folder in the popup, every bookmarked item in this folder should appear in the item list. But this is not the case right know if you reproduce my problem.

**Comment by madprops** [comment]
You're saying that no items appear, or that a normal 'search' is done instead of a 'deep search' ? If the latter, it's intended.

**Comment by N3C2L** [comment]
Oh, ok. I was thinking that all items in a folder would appear after I click an item from the popup list.
Yeah I think it does the normal search (for example 100 items) instead of the the deep search. Ok that explains it.

**Comment by madprops** [comment]
My reasoning being that you likely don't need to list 100+ items, except if you want to know the total, in which case you can just trigger a deep search manually to check. The auto deep setting kicks in when you type a query, since you're looking for something.

**Comment by N3C2L** [comment]
Ok but the only problem with this setting is, that sometimes no items at all will be displayed after clicking a folder. I think the "100" in a normal search only displays the latest 100 bookmarked files from the whole bookmarks in firefox.

**Comment by madprops** [comment]
Oh, you select a folder in `Select Bookmarks` with items, and get no item results? Yeah that's not right

**Comment by N3C2L** [comment]
Yeah, it's every folder that doesn't have one of the latest 100 bookmarked files inside. Maybe you can reproduce it by opening a very old folder in your bookmarks where you haven't bookmarked anything in the last years.

**Comment by N3C2L** [comment]
But you have to set "max bookmarks (searches)" to 100

**Comment by madprops** [comment]
Yes I'm observing the issue now. I'll try to fix it.

**Comment by N3C2L** [comment]
Thanks!

**Comment by madprops** [comment]
Yeah sorry about that, it wasn't filtering the folder at the right place. 

I'll upload fix soon.

**Comment by madprops** [comment]
Give `v3277` a try. It should fix the issue.

**Comment by madprops** [comment]
![_c8b4703a-919f-451f-bf8a-d951496c2c2e](https://github.com/user-attachments/assets/16afe37e-f579-462e-91d5-669a7a35332d)

**Comment by madprops** [comment]
I'm gonna make it so the selected bookmark folder gets resetted after leaving bookmarks mode.

**Comment by N3C2L** [comment]
HAHA, this pic is awesome 😁 
Sounds good the name change of the cmd.
Just noticed that after picking a folder with the bookmark select cmd (now Pick Folder),  then a deep search won't be automatically applied to only this folder/subfolders when I begin to type.

**Comment by madprops** [comment]
I'm gonna make the main menu button reflect the current folder (top left)

![stuff234](https://github.com/user-attachments/assets/86bd382a-2b0e-48da-8073-4718ff99b530)

I'm thinking about the subfolder issue.

**Comment by madprops** [comment]
Ok next version will have subdirectory search on deep search.

We'll see how performant that is.

Basically when you type a query and enter deep search, it finds all items through a recursive function.

**Comment by madprops** [comment]
Ok changes up in `v3281`.

**Comment by N3C2L** [comment]
Thanks, I enjoy this speedy recursive search. It's very fast filtering all the things in folders that have over 1000 items in different subfolders. And I can hit the space key to trigger a deep search if I need that quickly. You are right, an automatic auto deep search is not necessary for this folder pick because it's so fast anyway to trigger the deep search with a space key.

**Comment by madprops** [comment]
Interesting, wasn't aware of empty string searches. I'll optimize that a bit by keeping that behavior you like but without doing the string comparisons.

**Comment by N3C2L** [comment]
Hope it's ok to report some things here, 3 of them are related to bookmarks and 1 is a small other one.

1. There is a search bug in the bookmarks mode: At the moment it won't filter URLs (related to normal bookmark search and deep search bookmarks): steps: bookmark a url which have letters/numbers inside which are not visible in the title of the bookmark: for example bookmark this movie (love some of the zemeckis movies 😁) https://www.imdb.com/title/tt0096438/ . Then search for some numbers of this bookmarked url in the bookmark modes of GH. result: no results displayed in the item list. Also happens if special quotes is disabled in settings>more, I was thinking it was maybe happening because this was activated.
2. There is a conflict between cmds "bookmark"+ "to folder" when a bookmark rule was created before: steps: create a bookmark rule and bookmark a tab with it. then, go to a another site on the same URL and bookmark it with the "to folder" cmd in another folder: result: the url was not bookmarked in that picked folder (because of conflict with the domain & folder already set in the bookmark rule)
3. Small idea for the footer, enhancing the bookmarks mode: On item hover, the name of the folder where the hovered bookmark is located could be displayed next to the right of the URL. Long folder names could be truncated with dots or similar.
4. Thanks for the new menu in the settings! I'd be great if some of these could be added to cmds aswell. Because right now there is only the cmds "item menu" and "action menu" available as cmds that are useful for putting into the favorites bar. For example this could be added to the cmds palette: closed menu, history menu, bookmark menu, empty menu, footer menu. Then I could put these also into the favorites bar as cmds.

**Comment by madprops** [comment]
Next version will fix the first 2 big bugs, sorry bout that.

I'm thinking about the other 2 points.

**Comment by N3C2L** [comment]
Thanks for the fixes. 
About 4: Sorry, I wasn't meaning that these menus should appear in the settings. I was just thinking that these menus could be added to cmds, so that I can put these menu cmds into the favorite bar. So if I click in the favorite bar and there is a button with "empty menu" the empty menu with all the cmds will spawn.

**Comment by madprops** [comment]
Oh I understand now. Like `Browser Menu`. I already do that with some menus. I'll add a command for Empty Menu.

**Comment by N3C2L** [comment]
Because you mentioned the Browser Menu. I am often in the case, where I need to go back to the beginning of the browser history. I could use your cmd "Go Back" many times, which is located for example in the Browser Menu. But what if I want to go to the beginning of this browser history? My workaround for this is right clicking the left arrow on top of the ff browser:

<img width="98" alt="gfloorp" src="https://github.com/user-attachments/assets/7bd06b3d-188d-4e83-a5fb-972876dabd1e">


and then going all the way down until the beginning url of this tab. But do you think this could be much faster when implemented in GH? Something like a new cmd "Go Root" where it takes me all the way back to the beginning url of the browser history of this tab. That would be awesome.

**Comment by N3C2L** [comment]
Hmm, ok. It seems before firefox switched to webextensions, this was possible with an addon, but know it's not possible anymore also what is commented there in this addon:
https://addons.mozilla.org/en-US/firefox/addon/snap-back-button/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org

**Comment by madprops** [comment]
Ok `v3302` is up. Fixes and improved bookmarks searching.

Also new settings category: `Bookmarks`.

And new menu commands.

**Comment by N3C2L** [comment]
Ok, thanks.
1. Footer works fine in the bookmarks mode, all good, thanks.
2. New menu cmds are all good, thanks, altough I hoped you would add some more like I already wrote before above: footer menu, bookmark menu, closed tabs menu, history menu.
3. The bug with the bookmarks to folder is resolved, thanks.
4. But know is a big problem: The loading of a deep search has increased dramatically to more than 5 seconds, and still after 5 seconds the UI is not responsive, have to wait another 5 seconds until I can interact. Maybe it's because of the new URL filtering? But I think it would be more useful if you could reproduce that problem with many bookmarks. So there is an easy way for you to reproduce it I think (with duplication of your bookmarks):
1. Create a new firefox profile
2. Import all your bookmarks 
3. Go to the Bookmarks Manager of Firefox, Ctrl + Shift + O
4. Right click on the "bookmark toolbar" and click "copy"
5. Paste the bookmarks more than once in different folders
6. (If you have elsewhere more bookmarks than in the bookmarks toolbar copy and paste it from there to duplicate)
7. If you have maybe 10 000 bookmarks and 500 folders you can reproduce it.

**Comment by madprops** [comment]
Next version will have all the menus

Now I'm gonna read that bug you describe

**Comment by N3C2L** [comment]
Thanks, hope you can solve it.

**Comment by madprops** [comment]
Ok I finally found the problem. The new changed meant 5000+ items were being processed before filtering, that means creating the html elements etc, which is very slow. So now I go back to simple filtering before returning the bookmarks. Uploading soon.

**Comment by madprops** [comment]
Should be fixed.

**Comment by N3C2L** [comment]
You helped me a lot with this improvement. It's very fast again and a pleasure to use. Thanks!
