### ISSUE TITLE
Close Tabs by Time (not automatic)

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#13]
I know addons exist that close your tabs automatically in a specific time frame. But I hate the fact, that you have to always blacklist domains that should not be closed automatically. So I need another function: All the tabs I opened in the previous hour/today should be closed alltogether. This is helpful on days / hours when you doing researches that you know would not need any longer, but keeping the older tabs open.

**Comment by madprops** [comment]
The issue with this is that as far as I know, tabs don't have a date when they were opened
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab

**Comment by N3C2L** [comment]
I see. Maybe an option to close tabs that where loaded the last hour / day?

**Comment by madprops** [comment]
That would be lastAccessed variable. Would "close in the last hour" be enough or would you need more granularity? I can leverage the close tabs system I already built to add this mode.

**Comment by N3C2L** [comment]
Nice. Yes, appreciate "close in the last hour" but also I would be happy for "close tabs" that where last accessed in the last 12 hours (to mimic "today".)

**Comment by madprops** [comment]
Just to be sure. What exactly should be closed? Right now closing last hour shows a lot more tabs than last 12 hours. Is that correct?

```js
  let d = 1000 * 60 * 60 * hours
  let now = App.now()
  items = items.filter(x => (now - x.last_accessed) >= d)
```

**Comment by madprops** [comment]
Or maybe it's the opposite

**Comment by N3C2L** [comment]
Sorry, I could not describe it well. I think it is better for me if you can implement a "Close Loaded" command.

**Comment by madprops** [comment]
Close Loaded? What would that close?

**Comment by madprops** [comment]
There's currently a Close Normal mode, but it disables Pins. I could enable Pins to be an option. Check out what I mean by opening the `Close Menu`

**Comment by madprops** [comment]
There's also Close Visible that applies to all visible items.

**Comment by madprops** [comment]
I'm adding a Close Loaded close mode.

**Comment by madprops** [comment]
Added `Close Loaded` in the `Close Menu`, on version `990`.
