### ISSUE TITLE
Playing tab close warning problem

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#136]
I love the tab close warning features under settings > warns.
I have this settings enabled here on top:

<img width="294" alt="closed warnings" src="https://github.com/user-attachments/assets/303a5cc7-5614-48c0-a9c2-ad236a80cb99">

It's correct I want to have warnings on every special tab state like colors, pinned etc.
But I'd be awesome if there could be a seperate warning setting for closing playing tabs.
Because I want to have "special" enabled on top, but don't want to have a warning when I want to close playing tabs.

Another observation: I think there is a significant delay when the audio or video stops on websites like youtube and the playing icon disappearing some seconds later on the tab. Do you have the same delay when you pause a video on youtube, then look on the playing icon on the tab disappearing some seconds later?

**Comment by madprops** [comment]
Ok easy fix.

Right now special are: `item.pinned || item.playing || item.header`

I'm gonna add a checkbox for each to define if they should be considered special.

**Comment by madprops** [comment]
![speciakl234](https://github.com/user-attachments/assets/01307502-e3d3-47b0-92a7-dca633655ace)

**Comment by madprops** [comment]
Next version will have this:

![special234](https://github.com/user-attachments/assets/4ec60588-f36c-45b8-a0fc-1b80f1c96549)

**Comment by N3C2L** [comment]
Thanks for these options, very useful. It's so cool, because I have now a "locked" color assigned to every tab I want a close warning for. And with the "Browser" Hotkeys I even get a close tab warning when I am not inside the GH interface and try to close "locked" color tabs with the keyboard.

**Comment by madprops** [comment]
That's an interesting use

**Comment by N3C2L** [comment]
Unload cmd very important for me too, I have it on the hover button middle click, use it daily.

**Comment by madprops** [comment]
Ok new version `v3396` up.

Btw do you use GitHop? https://addons.mozilla.org/en-US/firefox/addon/githop/

It's useful to go back to github locations.

And the buttons can be configured.

**Comment by N3C2L** [comment]
Thanks for the new version!
Yeah, I know GitHop, one of your other addons, but haven't tested it much I think. Hmm, I think I would use it when I could change the background color in GitHop, cause black background hurts my eyes (I have astigmatism slightly). Or is there a setting for it to change the background color?

**Comment by madprops** [comment]
There's no way to change the theme yet

**Comment by madprops** [comment]
Ok in `v2.0` I added a theme setting you can change to `light`.

I took the opportunity to clean the code and bring it to current standards.

Some things I want to let you know about githop:

1) You can shift-click buttons to combine criteria.

2) You can modify the buttons to do different things.

3) It works with other git services, not only github.

4) Clicking the icons make items a favorite to have them in `Favorites`

5) It's completely based on recent History, so it won't find very old stuff although you can configure the history depth in settings.

**Comment by N3C2L** [comment]
Thanks!
I played with it a little bit now and like it so far. The features you described are all useful for fast navigating even on other sites than github if I want it to. However, do you you think it's possible that GitHop will also look at the open tabs when filtering? Advantage would be that we could switch to tabs faster in GitHop instead of open new tabs on click. Maybe an indicator in the item list that a tab with this url is already open could help also.

**Comment by madprops** [comment]
Ok it now shows tabs. Tabs and/or history can be turned off.

Tab and history can have icons. Default icon for tabs is "(Tab)".

Clicking a tab focuses the open tab.

The structure is tabs first at the top, then history.

**Comment by N3C2L** [comment]
Thanks, will check it out!

**Comment by madprops** [comment]
I decided not to use emojis since a quick test showed some weird renderings

**Comment by N3C2L** [comment]
Where did you see this, on scroll the list?

**Comment by madprops** [comment]
I guess it works. Unicode can be weird since the emojis can be composed

**Comment by madprops** [comment]
Thanks I'm gonna use that. I like that it has a history of recently used ones
