### ISSUE TITLE
All Settings view

### ISSUE THREAD

**Issue by madprops** [madprops/grasshopper#137]
Tomorrow I'm gonna work in an `All` (or something) category/view for Settings.

Idea is to view all the setting widgets in the same place so it's easy to filter/find them.

Not sure how easy this is going to be.

**Comment by N3C2L** [comment]
Great! Certainly valuable to filter through so much settings in a new All view!

A small idea I have also regarding a new settings cmd: Thinking of a cmd that takes me back to the setting position I was before the settings menu was closed. 

Advantage would be that we don't have to navigate through the settings again to access the last used settings position.

**Comment by madprops** [comment]
I'll see if I can add that settings command.

Right now All Settings is working. I decided instead of rendering all widgets, to show show the text of each, then you click the one you want and it focuses the correct category.

![textsettings](https://github.com/user-attachments/assets/9c2e8265-3a36-4c8c-8aed-ea5bf6eb3b06)

**Comment by madprops** [comment]
When you say settings position, is that only the category, or the scroll position as well?

**Comment by madprops** [comment]
Ok I'm adding `Last Settings` command.

It goes to last category, restores filter, and scrolls to last scroll 500ms later.

**Comment by madprops** [comment]
Also adding it to the settings menu:

![settingshq34](https://github.com/user-attachments/assets/e4b70b29-2319-4f47-9668-d0dd645bc4ef)

**Comment by madprops** [comment]
New iteration

![allsettings1234](https://github.com/user-attachments/assets/3687f78c-b631-4b71-9286-bb6ff14a97e2)

**Comment by N3C2L** [comment]
> New iteration
> 
> ![allsettings1234](https://private-user-images.githubusercontent.com/206498/373210959-3687f78c-b631-4b71-9286-bb6ff14a97e2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTE4NDgsIm5iZiI6MTcyNzk1MTU0OCwicGF0aCI6Ii8yMDY0OTgvMzczMjEwOTU5LTM2ODdmNzhjLWI2MzEtNGI3MS05Mjg2LWJiNmZmMTRhOTdlMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMDMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGYxYTM2ZGQ5YTMwNmI1ZTBkNmFlMmMzMGFhYTQ2YWM1OTAxYzE2NzkyMjBiMzUyZTcxMDUwNjk1NmIyOWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hrwJXgNnC9DD7k1z6OpJqkcXcb8cu12F6_Ps0eOnqpI)

Great! With that, you can quickly find it and jump to the spot.


> Also adding it to the settings menu:
> 
> ![settingshq34](https://private-user-images.githubusercontent.com/206498/373195224-e4b70b29-2319-4f47-9668-d0dd645bc4ef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTE4NDgsIm5iZiI6MTcyNzk1MTU0OCwicGF0aCI6Ii8yMDY0OTgvMzczMTk1MjI0LWU0YjcwYjI5LTIzMTktNGY0Ny05NjY4LWQwZGQ2NDViYzRlZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMDMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjY2OWMxMTExNzEwZWIwZmYxZWFlMTYwZDRmYmNmMzYyMDFiZmM1YjM4YjIzMWQwY2UzYTk3NGUyZDc4MzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gwTJbQSKauQf79UtNu-qV4JUMbkkewaixarZFVxJ-4U)

Thanks, looks also very good to me! Looking forward to put this cmd in the favorites bar 👍

**Comment by madprops** [comment]
New version is up.
