### ISSUE TITLE
Favorites Folder Box & Favorites History Searches Box

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#138]
Thanks for all the features you already implemented on the tab box. What do you think to transfer some of these features to a new folder box & history box? Or maybe we could use the tab box for this? Some thoughts I gathered on this and maybe you like them too:

1. Favorites Folder Box would be automatically visible when switching to the Bookmarks Search Mode. This Folder Box contains Favorite Folders, which a user can define in a Favorites Folder Box menu. This menu can be filled with a list of favorites folders in the settings. When a folder is clicked inside the Folder Box, the item list will show this folder content (same content visible as someone would run the Pick Folder cmd and choose a folder).
2. The History Box would be automatically visible when switchting to the History Search Mode. This History Box contains the list of the favorites history filter, which a user can define in a new history filter menu.  If a user clicks on a favorite history search item in this history box, the item list will be filtered with this selected term.

The advantage with this boxes is, that they are easy accessible when switching to the History & Bookmarks mode. It would be also superior to any bar solutions on top, because the space with a new history bar & bookmark bar would be limited.
Also with the nice auto-grow feature from the tab box, these boxes could be easily
resized to be large and small and wouldn't disturb the item lists.

Edit: The tab box / folder box could also be enhanced with "last created folders" and "last used folders" (folders that have been last accessed with the "pick folder" cmd for example).

**Comment by madprops** [comment]
The other boxes seem to clash with other existing features.

For history you could make custom filters or aliases, or right click filter.

For bookmark you can use bookmark picker.

**Comment by madprops** [comment]
However I understand the requirements you describe. 

I'll let you know if I implement them.

**Comment by madprops** [comment]
That's quite an interesting idea.

**Comment by madprops** [comment]
![domaines](https://github.com/user-attachments/assets/1bb07520-a7c7-4243-ad8e-8ad943b19423)

**Comment by N3C2L** [comment]
Wonderful there, thanks.

**Comment by madprops** [comment]
Also added an auto shrink setting to tab box. If no items then shrink to selected size. If items then use normal size.

**Comment by N3C2L** [comment]
I think this can be closed for a while until you want to implement it some day later.

**Comment by N3C2L** [comment]
You may want to take a look at the bookmark panel function in sidebery in the future. When you right-click on a bookmark folder there, you can create a "bookmark panel" from it ("open as bookmark panel"). This bookmark panel then becomes visible and clickable on a button in the toolbar. This means you can jump directly to a bookmarked folder via this bookmark panel. This might help you with implementing a folder box, or perhaps someday displaying folders in the item list. With folders in the item list, it would be benefical to double-click on a folder and that folder would then be displayed, just as it currently is in file browsers.

Idea for the History Box in the future: If a tab is selected, the history box shows all the history urls from the tabs domain.

**Comment by madprops** [comment]
I think there might be room for special modes.

But I think I wouldn't make another "box".

I would consider a boomarks mode for the "tab box".

**Comment by N3C2L** [comment]
Great to hear that you want to enhance the tab box with bookmarks!
I'd love to give feedback/ideas for this. What bookmarks mode you want to show in the tab box?

**Comment by madprops** [comment]
I'm thinking of a Folders mode to show recently picked bookmark folders.

And maybe a History mode and a Bookmarks mode, each with recent searches performed through the filter. Though I'm not sure about those.

**Comment by N3C2L** [comment]
I find all three great. But even the last two, where you're not sure, have the advantage of being more separate from the filter bar, because there the history of filterings of tabs, bookmarks, and history are mixed together. When you right click the filter bar you never know if it was a search for the tabs, bookmarks, or the history mode.

**Comment by madprops** [comment]
Yeah I agree. I have Folder mode working:

![folder2q4](https://github.com/user-attachments/assets/8c17b071-54b9-4907-b719-342e7960fb86)

**Comment by N3C2L** [comment]
Awesome! 
An automatic switch to this folders when entering the bookmarks mode would be neat.

**Comment by madprops** [comment]
Done, and it will remember the previous tab box mode, so when you go back to tabs or whatever it restores the previous tab box mode instead of getting stuck in folders mode.

**Comment by N3C2L** [comment]
Fantastic! Thanks!
I can give some feedback tomorrow, since it's getting late here and I need some zZz.

**Comment by madprops** [comment]
What I did is add a Save Folder in bookmarks action menu and Save History in history actions menu. So they are added manually.

When in bookmarks inside a folder, using save folder will at it to a list.

When in history, save history will save the current query used to search.

These items can also be removed manually by middle clicking the tab box items.

**Comment by N3C2L** [comment]
Thank you again for this save to folder & save to history implementations!
Thanks also for the new tab box cmds that can switch to other tab box modes, and also thanks for the compact mode.
Remember that I want to help to enhance GH with my bug reports and feedback and I don't want to disturb you. You can always say to me: I'look into it tomorrow, in some days, next week, etc. I understand this.

The first 4 are small bug reports, other 2 are small "feedback" points, maybe you like to do something with it or not.

1. I think there is a bug with the tab box auto folders & history settings: please run the GH popup in bookmarks mode (the browser shortcut from the about addons firefox site), and go to "recent" mode in the tab box. close the GH popup and then reopen this GH popup with the same shortcut again. Result: The tab box mode is back at "recent" again and not in "folders". Same result when the GH popup is ran with the history mode with the browser shortcut from the about addons site.
2. When executing "Pick Folder", the filtered list does not display the bookmarks in the subfolders of this folder. The same occurs when running the "folder search" command.
3. I guess there is a menu bug with seperators: I can only insert a single separator in all menus; additional ones do not appear.
4. Possible Copy+Paste tabs bug: Please copy one or more tabs with the "copy tabs" cmd. Select the last tab in the item list. Try to paste the tab. Result: It doesn't paste the tab below this last tab. It's not a right click menu problem, because it's also not working when executed via cmd palette when this last tab is selected.

Feedbacks:

 1. I think every item in other tab box mode than folders & history is text left justified and with icon. I think text left justified is quicker to spot than centered, because the item list above is also left justified. Icons would be crucial to quickly know if it's a history item or a bookmark item in the tab box.
2. Tried and failed to do a combo containing "Pick Folder" + "Save Folder". I can't do this, since the "Pick Folder" forces me to choose a folder first which needs time, so that "Save Folder" cmd afterwards would be executed when I am still in the "Pick Folder" popup. Possible solution could be a seperate "save folder" cmd where the folder list from the "pick folder" list would spawn to add them to quickly to the tab box.

**Comment by madprops** [comment]
I don't understand 2. And can't repro 4

**Comment by N3C2L** [comment]
Thanks for the fixes!
Regarding number 2: Choose a folder from your bookmarks that also contains subfolders. These subfolders also have bookmarks inside them. Previously, with the "Pick Folder" command, when a folder was called up, the bookmarks within its subfolders were also listed. This is similar to viewing a "Flat" view of one of your folders in a file browser program (e.g., Directory Opus). In this "flat" view, you would also display the contents of all its subfolders.

**Comment by madprops** [comment]
I created a subfolder inside a folder and I see it when I use Pick Folder.

**Comment by N3C2L** [comment]
Yes I can see the subfolders in the "Pick Folder" popup. But you are right, I mean the list of bookmarks where title and urls are, not the folders.

**Comment by madprops** [comment]
Is this after triggering deep search with a query? Auto deep search bookmarks kicks in after a query. As you said before you could press space to reveal sub items. Is this the case?

**Comment by N3C2L** [comment]
Ah, right. I forgot the space key trick for this. It's working with this one.
Are there any plans in the future for displaying folders in the item list or are there any technical limitations?

**Comment by madprops** [comment]
No plans for that

**Comment by N3C2L** [comment]
And why?

**Comment by madprops** [comment]
Well. I guess listing an item that is a folder is not that complicated. Maybe I'll try something.

**Comment by N3C2L** [comment]
Nice! These folders there in the item list would be a great upgrade!

**Comment by madprops** [comment]
Ok it's working. I'll give it a special folder favicon

![folderj234](https://github.com/user-attachments/assets/16a12a83-bea5-4afd-b202-3bf5358ce46f)

And I guess i'll add a setting to filter those out or not.

**Comment by N3C2L** [comment]
Wow, what a quick implementation! I'm thrilled! Yes, folders at the top would certainly be a good viewing option. Or maybe last created is also possible, where bookmarks and folders are mixed on top, last created of these two on top?

**Comment by madprops** [comment]
Right now it's using dateAdded sort

**Comment by madprops** [comment]
This is going to be a huge update.

The bugs are fixed.

Tab Box is better now.

History and Folders in tab box can be re-ordered by mouse.

Bookmark folders.

Shrink only on mouseleave to allow mode wheel.

Toggle bookmarks command.

Other fixes.

**Comment by N3C2L** [comment]
I really like this stuff, thank you again. Excited to try out the update tomorrow.  Can't do it today because I'm about to go to zzZleep. I can write some feedback about the update tomorrow. 
Thanks for doing this addon!

**Comment by madprops** [comment]
On another update I'm adding empty menus for all modes. The ability to create folders when inside a bookmarks folder.

**Comment by N3C2L** [comment]
> On another update I'm adding empty menus for all modes. The ability to create folders when inside a bookmarks folder.

Great! Good ideas!

---

I have tested the latest update.

The folder navigation within the item list works very well; one can easily navigate back with the step back button or with the new parent folder command. Also, thank you for the ability to save a folder directly to the Tab box when right-clicking a folder in the list, that works well. 

Thank you also for left-aligning the text and the icons in the Folder mode and the History mode of the Tab box, as well as the ability to change these icons in settings > icons!

The new toggle bookmark folder command is great!

The moving of folders within the Tab Box and also in the History mode of the Tab Box is wonderful. Users can nicely organize everything to their liking.

**Comment by madprops** [comment]
Sorry the empty menus were bugged out and weren't appearing . Just uploaded a fix.

Also glad to hear you approve of the new stuff.
