### ISSUE TITLE
Active Tab in the Tab Box

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#15]
It would be great if I could see the active tab in the tab box (or seperated from the tab box):
When you are filtering the list, the actual focused tab could be hidden because the filter does not match the active focused tab search criteria. Instead of going back to the previous view where the active tab is focused, you can click a button in this new active tab area and make there quicker actions without losing your actual filter search.
Commands that would be available the same as when doing a right click on an active tab, but without having to navigate to the active tab (because the active tab is hidden due to the filter).

**Comment by madprops** [comment]
Ok so you want the active tab to also be included in the tab box. And you want right click menus. That's what I understand right now.

**Comment by madprops** [comment]
I'm adding a setting to include that active tab. It will be true by default. I added context menu to items. Will be available in v995

**Comment by N3C2L** [comment]
Wow, thank you!

**Comment by N3C2L** [comment]
Tested it now and works, thank you. One thing: The right click on a tab item is most used by users I think. Maybe do you want to implement the option, that we can customize the right click menu like other menus? That would be fantastic.

**Comment by madprops** [comment]
In `Menus` there's an `Extra` menu. This one appears on the bottom of the item menus.

![extramenu](https://github.com/madprops/grasshopper/assets/206498/3effe0e1-fc76-4111-a984-8ea962a29ba5)

**Comment by N3C2L** [comment]
That's valuable, thanks. Although I would have preferred not having to click "extra" first when right click. Maybe you can bring the commands customization on the first level like the other commands when right clicking an item?

**Comment by madprops** [comment]
No I don't like that, it messes with the width and looks weird. But it's easy to add a setting to do that. I'll add it on `Menu` called `Flat Extra` checkbox. On next version.

![extra234](https://github.com/madprops/grasshopper/assets/206498/334210f1-0ca4-44ac-a9d9-3451374ac141)

**Comment by N3C2L** [comment]
Much obliged.

**Comment by N3C2L** [comment]
Perfect addition, thanks a lot!
