### ISSUE TITLE
Bugs: Icons / Seperators / Bookmarks

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#150]
I have some GH problems, hope you can look into it:

Please go to Settings > icons, then delete the unloaded icon from there. close settings, open the cmd palette, search for unloaded: result: the icon for unloaded isn't there. icons deleted from settings>icons  are deleted from the cmd palette and from menus. expected result: deleted icons from the icon settings should be remain visible in menus and cmd palette but not on tabs. I can reproduce the problem for unread icons also.

I tried to add some separators to the bookmarks favorites bar menu, but the seperators are not visible afterwards in the favorites bar itself when exiting the favorites settings. Please repro: Add some seperators to the bookmarks favorites bar menu, then exit the settings an look at the bookmarks favorites bar in the Bookmarks mode of GH.

When I open the GH bookmarks mode for the first time, new created folders are not included in this standard view. Please repro: Create a folder inside or outside GH, then switch to the GH bookmarks mode. 

Offtopic Question: You made the ff Hacker News addon that will open links always in new tabs when clicked. Awesome! But do you use something similar for the youtube website?
I desperately tried other ff addons doing the same for the youtube domain, but without success. 
I tried it with this old ff extension, but it's not working on yt reliable :
https://github.com/ramkumar-kr/open-in-new-tab
And tried it with this old ff extension, it's not working at all on youtube:
https://addons.mozilla.org/en-US/firefox/addon/open-link-with-new-tab/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser
This plugin is the best from these 3, but also not working on youtube:
https://addons.mozilla.org/en-US/firefox/addon/open-links-in-new-tab/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser

I know I requested much lately, but if you are interested in creating something different. Same like your ff HN addon but only for youtube, open links in new tab. Only if you like the idea of course. 😁

**Comment by N3C2L** [comment]
Domain Rule bug:
Please create a Domain Rule + checkboxes enabled: "Exact Match" + either "Split Top" or "Split Bottom" or both (doesn't matter). Result: If the domain rules match, the split top or split bottom is not visible in the tab list.

**Comment by madprops** [comment]
I recently changed how icons work. You're not supposed to delete the icons. Rather just change its visibility.

**Comment by N3C2L** [comment]
Ok, thanks.

**Comment by madprops** [comment]
`HN addon but only for youtube`

Maybe when I'm bored i'll do it. Though I could teach you how to make one for any site, it's easy. The hardest part is having a firefox account to upload.
