### ISSUE TITLE
Some problems on header tabs, copy & paste, reload pages, domain rule.

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#153]
I guess I found some bugs / problems.
I prefer to put more than one bug in a thread so I don't need to open an issue for every little bug / problem.
Hope that's ok.
Sorry if something isn't a bug. But hopefully one of them so that the thread wasn't in vain 😁 

1. Closed header tabs are not visible in the closed tabs mode of GH.
But other closed moz-extension tabs are listed in the closed mode of GH if closed.

2. Copy and paste is currently not working in combos. With or without sleep cmds between the cmds, doesn't matter.

3. Cant reload more than one tab with the "reload page" cmd, and also not working in a combo. (I use that to refresh a whole zone with that combo).

4. The cmd "domain rule" isn't working on a tab. It doesn't show the domain rule interface after executing the cmd on the tab.

**Comment by N3C2L** [comment]
Great. I knew it, grasshoppers eat bugs. No one can tell me otherwise.

**Comment by madprops** [comment]
It's a tough beast

**Comment by madprops** [comment]
Took a while to fix some bug regarding jumping to headers.

**Comment by madprops** [comment]
Ok fixes uploaded

**Comment by N3C2L** [comment]
You are awesome, thanks! I'll update asap and enjoy the fixed version!
