### ISSUE TITLE
Tab sort & save folder problem

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#154]
I currently love your great new "Toggle Sort" cmd, it's really handsome to switch between normal and recent with the mousewheel in the favorites bar with this new cmd! Thanks!
But one little thing makes the active "Recent" tab list hard to read (when "Tab Sort" is set to "Recent"), because the listed header tabs in the tab item list of this "Recent" view do not fit there I think. Because the visible header tabs make only sense in the index ("normal") view of the sort view, but not in the "Recent" option. Because only in the Index ("normal") view the header tabs are connected to the tabs below, not in the "Recent" view.
Therefore I'd prefer to exclude header tabs from this "Recent" view, if you don't mind to implement an option for that. That would make it even more awesome for a better overview in this "recent" sorted tabs view. Else people with lots of headers couldn't make a great use of the "Recent" option.
Another visual enhancement to this sorted tab views could be: To display the name  "Recent" at the top in the filter menu button when a tab sorting is activated. This way, one knows that the tabs are sorted atm, perhaps also with the active filter effect in the filter bar.

When I execute the "Pick Folder" cmd, and then try to save this picked folder into the tab box afterwards with the "Save Folder" cmd, it doesn't show the saved folder in the tab box. It's currently only working when right click another folder inside this picked folder and run the "Save Folder" cmd.
But I think this was possible in a prior GH version. Because the problem with this is currently: When I already searched ("Search Folder" cmd) or picked ("Pick Folder" cmd) a folder, why one shouldn't be able to save this picked or searched folder to the tab box afterwards?
Please try to reproduce the problem above with this steps:
1. Open a large folder that also contains subfolders using the "Pick Folder" command.
2. After you have picked a folder, call up the Command Palette and run "Save Folder".
3. Result: The first subfolder is saved in the Tab Box, but not the folder you previously selected under "Pick Folder".

A solution could be a new "Pick & Save Folder" cmd where the picked folder will be automatically saved to the tab box afterwards.

Another solution could be a new breadcrumb bar on top of the Bookmarks Mode of GH displaying the parent tab and subfolders in a hierarchy like we know it from file browsers:

![image](https://github.com/user-attachments/assets/9ab5b5b0-72df-4d3a-94a7-228f367fea71)
When right clicking these folders in the breadcrumb bar options like "Save Folder" could be visible. Left clicking on these folders in the breadcrumb bar filters that folder in the item list.

**Comment by madprops** [comment]
1) You're right, I'm removing headers from recent sort.

**Comment by N3C2L** [comment]
Sounds good. Thanks!

**Comment by N3C2L** [comment]
Tested it today and it's good! Thanks! I think I can close this.
