### ISSUE TITLE
Tab Lock

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#16]
Option to lock a tab: When navigating from a locked tab, a new tab always opens when clicked on a link inside the website. A lock symbol may useful as an indicator on the tab item.

**Comment by madprops** [comment]
I see. If a tab's profile has lock:true it should open tabs in a new tab. I'm not sure I can control how tabs are opened within the extension though.

**Comment by N3C2L** [comment]
I don't know, because I am not a developer. I know just a little CSS here and there. But I would be happy if you can implement it.

**Comment by madprops** [comment]
Yeah I understand the feature but I don't think it's possible. The way tabs are open is dependent exclusively on the browser (as far as I know).

**Comment by madprops** [comment]
![Uploading content234.jpg…]()

I think they achieve this by injecting a content script to every tab. I don't inject or plan to inject anything to websites.

**Comment by madprops** [comment]
![content234](https://github.com/madprops/grasshopper/assets/206498/da23ea7d-7239-43a5-819a-fb616ffbc608)

**Comment by N3C2L** [comment]
I see. Thanks anyway.
