### ISSUE TITLE
Unread + Unloaded Tabs indicators

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#17]
I know that you have already implemented an icon for unloaded tabs. But I would prefer this: Unread tabs are underlined (dotted) and unloaded tabs have red text titles.

**Comment by N3C2L** [comment]
Maybe if you implement a custom css section for users than we can change this for ourselve if we want to.

**Comment by N3C2L** [comment]
Maybe you want to implement a new color category in the settings menu called "titles". Here you can change the title text color for: unloaded, loaded, unread and so on.

**Comment by madprops** [comment]
Alright, started implementing this. Right now I'm adding color pickers for pins, normal, loaded, unloaded, playing. Not sure I want to do `unread` since that's not a thing I deal with right now.

**Comment by madprops** [comment]
What do you mean by unread?

**Comment by madprops** [comment]
Version `1004` now has a `Colors 2` settings category. This changes the text color of items depending on type. Some colors take precedence over others, for instance `Playing` has higher priority than `Pinned`, these might need adjustments.

**Comment by N3C2L** [comment]
Thank you! Sounds interesting the hierarchy thing. The unread filter type is interesting because I know it only from this perspective: You open a link in a new tab in the background (instead of open the link in a new tab in the foreground). So every link opened in the background tab are marked as unread.

**Comment by madprops** [comment]
Right now all tabs are marked as unread on startup. Should it only apply to new tabs opened?

**Comment by madprops** [comment]
Ok new version improves `unread`. Also this is how the hierarchy is:

`Playing` is highest priority etc.

![colorhier324](https://github.com/madprops/grasshopper/assets/206498/4058c440-28da-43b1-862d-01aa07992020)

**Comment by N3C2L** [comment]
I love this addition, thank you.
