### ISSUE TITLE
GH popup delayed with many tabs

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#176]
I have over 300+ tabs open in the sidebar and have a 3 second delay when opening the grasshopper popup for quick searching tabs or recent tabs. 
I have the ff sidebar hidden and revealed on hover with the mouse so that's why I am using primary the grasshopper popup when filtering tabs quickly with the keyboard and not the sidebar.
I am using the browser shortcuts for opening the GH popups and it's working good but there is a 3 second delay. I am thinking it's because there are lots of tabs that have edits, like colors, custom title, notes, tags and header tabs.
When I execture the GH shortcut for the popup: First thing is that the GH interface for the popup is shown, but blank, then 3 seconds delay, and then the tabs are visible.
I don't know what could be the solution exactly but maybe one of these help:
Plain tabs are loaded first and then in a second step the edits of the tabs are applied (color, tags, notes etc).
Or maybe another approach could be that not all 300 tabs are loaded at once when the GH popup appears, but only the first 20 tabs or less to just fill the popup with something. And then step by step the other 280 tabs will be loaded some milliseconds later when the interface is already fully loaded and filled with some tabs.
I hope you would like to look into this problem.
I'd be glad if you want to reproduce it and create also 300 tabs 😁

**Comment by N3C2L** [comment]
Great to hear that you could reproduce it and thanks for doing more tests tomorrow.

**Comment by madprops** [comment]
Let me know if it's faster for you now. Hopefully this doesn't introduce nasty bugs.

**Comment by N3C2L** [comment]
It's perfect now, thanks!
The popup is there instantly afer I run the shortcuts. No more delay visible also on the other modes like bookmarks mode and history mode. I haven't encountered any nasty bugs, but if I finde some I'll report them here. 👍
