### ISSUE TITLE
Headers visible on recent sort & Autoclick to top & auto scroll tab box

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#177]
Please enable "recent" under general>tab sort>recent.
Create some headers, they are visible here but I have set them hidden in the zones settings.
Second problem is that autoclick is a little problematic when tab sort is set to "recent". Because when a tab item is activated with autoclick, the tab jumps to the top of the list and could activate the next tab in the list (because the mouse cursor is landing on another tab), and then again this tab jumps to the top of the list and so on. You can reproduce that by activating autoclick on "item autoclick" in the autoclick settings and toggle to the recent view. This could be solved with a little new setting that an activated tab is only jumping to the top of the list when the mouse cursor moves outside of the GH sidebar/popup. With this solution autoclick and the toggle tabs to recent option could work better together. 
Another problem is when auto scroll is disabled with the toggle auto scroll cmd it shouldn't be disabled in the tab box when clicking an item. You have already implemented a setting in the tab box settings area for this, it's called "Tab Box Focus". I have activated this setting, but when auto scroll is disabled, this setting isn't working.

**Comment by madprops** [comment]
Ok first issue fixed

**Comment by madprops** [comment]
Second issue fixed

**Comment by madprops** [comment]
I need more info on the last issue because when I turn off auto scroll, and say, I click an item in Loaded, it does scroll (in the tab box)

**Comment by madprops** [comment]
Can you describe what you are doing on the last issue regarding tab box focus. What do you click, where, what do you expect to happen. Which tab box mode?

**Comment by madprops** [comment]
Ok I guess you mean you click an item in the tab box, and it is not auto scrolling in the main view.

**Comment by madprops** [comment]
Ok some fixes on the tab box on autoclick.

**Comment by N3C2L** [comment]
> Ok I guess you mean you click an item in the tab box, and it is not auto scrolling in the main view.

Yeah, exactly. I am sorry that I wasn't clear enough on this. Thanks for this fixes, I'll try them out asap.

**Comment by madprops** [comment]
Ok it's uploaded.

**Comment by N3C2L** [comment]
Thanks for your last fix with recent tabs.
But I think I found another problem for this recent tabs view:
Please try to reproduce:
1. Switch to "Recent" view in the tab sort mode
2. Load an unloaded tab from the middle of the tab list
3. Move the cursor out of the sidebar (the activated tab will now move to the top of the item list, that's good)
4. Move the cursor back in the sidebar again
5. Problem: The activated tab is on top of the item list but the auto scroll is on the same position where we clicked the tab before. The auto scroll should focus the activated tab when entering the sidebar with the mouse again. Of course this scroll to top when entering the sidebar again should only happen in the "Recent" view where users would like to be on top most of the time because the loaded tabs are there for fast switching. Otherwise I would have to scroll to the top every time I re-enter the sidebar again. If you don't want that behavior by default, I'd be glad for a little new setting for this.

Second problem:
The header tabs in the tab box aren't renamed when the browser restarts.
Please try to reproduce:
1. Create and rename some headers with the edit title cmd (sort tabs to "index" before in the general settings, not "recent")
2. Restart the browser
3. Look in the "header" section in the tab box
4. Result: The headers edited names are visible only again when clicked on these headers in the tab box or when a new header tab is created. Currently when the browser restarts all headers are named "header" and don't have the edited name from the edit title cmd.

**Comment by madprops** [comment]
Ok so first problem is to make it scroll to the top, on mouse out, on recent mod. Makes sense.

**Comment by madprops** [comment]
I can't reproduce problem 2. I create some headers. Give them a a title. Restart browser. Check tab box. Headers section. They are titled correctly.

**Comment by N3C2L** [comment]
> Ok so first problem is to make it scroll to the top, on mouse out, on recent mode. Makes sense.

Thanks.

> By the way, did you know about the default shortcut to go to Recent mode by click and holding the main menu?

Great, I didn't know that.

> I can't reproduce problem 2. I create some headers. Give them a a title. Restart browser. Check tab box. Headers section. They are titled correctly.

Hm, ok, maybe I have "old" headers that where created before your observer update. I'll do some more header tests in one hour and report back then.

**Comment by madprops** [comment]
Maybe you do some different steps. When do you open the tab box, is it always on headers mode, does it require to change title in some way. I doubt it's the observe change but idk.

**Comment by N3C2L** [comment]
I do think it's because of the observer. Because I enabled "Fill Elements" under "More" testwise, and when I enabled this and then exited the settings, the headers in the tab box all got renamed to their edited title. But I do need the observer because it's faster with many tabs.

**Comment by madprops** [comment]
Oh ok, i'll take a look with that in mind.

**Comment by madprops** [comment]
Ok I found the problem. I'm uploading the new version soon.

**Comment by madprops** [comment]
Ok it's up. Thanks for catching this, and keeping track of added settings, idk how you do that

**Comment by N3C2L** [comment]
> Ok it's up. Thanks for catching these, and keeping track of added settings, idk how you do that

Thank you so much! Yeah I love all these options and on update I take a look on the settings you implemented 😁

**Comment by N3C2L** [comment]
I thank you for the implementations and don't want to bother you today with another.
But maybe tomorrow it would be cool if you could look into this problem:

I use the GH popup to search for tabs and then the popup closes and then I use the sidebar for further navigating. But the problem is, that when I activate a tab through the GH popup, it doesn't scroll to the top in the sidebar (when sort tabs > "recent" is enabled). But it's successfully scrolling to the top inside the GH popup when activating the tab there.

**Comment by madprops** [comment]
I'm not reproducing this. Are both sidebar and popup on recent mode? Does your popup close when activating a tab? Here it is scrolling in the sidebar normally.

**Comment by N3C2L** [comment]
Thanks for the fix.
Here are my steps for the current problem, just in case if the problem still persist with your fix, please try to reproduce:

1. Open the gh popup, switch to recent mode, click an unloaded tab, the gh popup will close
2. move the move cursor into the gh sidebar (recent mode before activated) and in my case the auto scroll to top isn't visible here, the tab is on the same place where I clicked it in the GH popup but not on top of the item list in the sidebar.  It seems that the tab activation doesn't synchronize the scroll on top action on both sidebar and popup on click. When you click in the unloaded tab in the GH popup is the auto scroll to top happening in the sidebar without moving the cursor inside the sidebar? In my case I need to move the mouse 2 times outside of the GH sidebar (after the popup click on tab and popup close action) and then again inside the sidebar and the tab is jumping on top. I tried it with other cmds like "select item" in the GH popup. When I do this then it selects the item tab in the GH popup but not synchronized in the GH sidebar. (Tab is not focused there in the sidebar with this cmd) Do you think you could synchronize this actions, because you already implemented under "More" > "Mirror Settings and "Mirror Edits?"

**Comment by madprops** [comment]
Let me know if it's fixed now

**Comment by N3C2L** [comment]
Yeah thanks, It's great now!
When I activate a tab in the GH popup it's jumping instantly on top also in the sidebar.
