### ISSUE TITLE
Quick close button

### ISSUE THREAD

**Issue by fireworksordie** [madprops/grasshopper#2]
Just found this extension and love it- I've been trying to identify an extension as simple but useful for a while and have ended up with an abomination of TreeStyleTab and a bunch of addons for it. This seems great.

Would love to know if you can either add a quick close X-style button that could be toggled for use instead of Pick (love the pick feature though - maybe the X appears where the favicon is in the list?) or to know if there's a means to do this already that I'm not seeing.

Currently the steps to close a tab are: 

hover -> right click -> close tab

but I'd love

hover -> close tab button

for quick closes.

**Comment by madprops** [comment]
Hi, thanks for the report. This is an interesting request and I think it makes sense. You can also close tabs with middle click but a button might be easier.  Putting a Close button on the favicon side (left) would be weird I think. The close button would need to go where Pick is.

I'm thinking 3 things:

1) Remove Pick altogether (and maybe add it to the context menu), put a Close button instead.

2) Have a setting of what the button can be, Close, or Pick. 

3) Have the button be something different on each context, Close for Tabs, Pick for History, etc.

Issue with some of these is that Close would only make sense in Tabs, it wouldn't make sense in History for instance.

I'll keep thinking on this and test it a bit. Let me know what you think.

**Comment by fireworksordie** [comment]
The middle click is a huge tip that I should have tried, didn’t even think about it.

I agree that the close button should stick to the right side where Pick is currently. But I also  think it doubling the favicon as a checkbox for Pick might be decently intuitive if you wanted to keep it clean.

Otherwise, an option to either always show an actual checkbox to the left of all favicons or only in “Pick” mode (have there be a Pick mode button - maybe even just an icon - on the top bar next to the menu and such) would be perfect. If given the option with always displaying the checkbox I see myself keeping Pick mode active regularly because I’m pretty constantly needing to blow away a bunch of tabs.

**Comment by madprops** [comment]
This is how it is right now:

There's a pick icon on the left side (more comfortable than picking icons). The icon can be customized in settings.

![pickdemo2](https://github.com/madprops/grasshopper/assets/206498/dba13459-31fd-4040-9599-36dae682a280)

The button on the right now shows Closed on tabs, and Open (previously called launch) in others.

![closebnt](https://github.com/madprops/grasshopper/assets/206498/cbd25f8a-aa62-4b68-85ba-5cc3f78d7431)

Both pick and "alt" buttons can be enabled/disabled in settings. Enabled by default.

**Comment by fireworksordie** [comment]
Love that. And if you want to go even lighter the Close overlay could just be a nifty lil X like what TST does (if I recall correctly). Looks killer though. You got a donation link?

**Comment by madprops** [comment]
Alright will upload soon. 

>You got a donation link?

I don't at the moment.

**Comment by fireworksordie** [comment]
I love when devs have a ko-fi.com link. Super low effort to throw some cash your way. Don’t hesitate to set something up - I bet it’s not just me! Especially since I think a ton of other people would find this extension as useful. And thanks again!

**Comment by madprops** [comment]
I noticed I tend to click on the left side of tabs to focus them sometimes. The pick buttons got in the way. I decided to keep it but it's disabled by default. You can enable it in Basic Settings. Also I added a way to select a range with the picker, press the mouse button on one then drag up or down.
