### ISSUE TITLE
Filtering bug when tab is colored via tab box

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#20]
How to reproduce: 
1. activate tab box, switch to all tabs.
2. color some tab items red.
3. click on a tab that has no color.
4. switch to "all color" filter.
5. navigate to tab box, right click on active tab and choose color red.
6. expected result: the previous colored tab from the tab box should be visible in the "all color" filter above.

**Comment by madprops** [comment]
I think I might have fixed this by fixing another bug regarding the filter menu being duplicated. Will upload v999 soon.

**Comment by N3C2L** [comment]
Bug still exist: Yes, you can colorize a tab from the tab box only when the list above is set to "All". But you can't colorize a tab from the tab box when other views are visible above like "Normal" or "All Color".

**Comment by madprops** [comment]
I tried with `All Colors`, the list did get updated. But i'll do more tests.

**Comment by N3C2L** [comment]
Did you try to set the view to "all colors" first, and then navigate to the tab box and colorize it?

**Comment by madprops** [comment]
Oh you're using Extra menu to color I think not Edit. That's acting weird right now.

**Comment by N3C2L** [comment]
Yes I am using the Extra Menu, thanks for fixing.

**Comment by madprops** [comment]
This should be fixed now. Also: https://github.com/madprops/grasshopper/issues/23

**Comment by N3C2L** [comment]
Thanks but problem now is: When using command "Color Red" it colors all tabs from this domain not just the single tab.

**Comment by madprops** [comment]
If the tabs have the same URL it will apply to them. The profiles are associated to domains not tabs per se. You play with the profile URL to make the matching be more general or more exact, but this is the way profile works, since it should persist between restarts instead of coloring tabs all over again.

**Comment by N3C2L** [comment]
Ok, thanks. I think the problem was that the tabs shared the same domain, but they differ in the url. That's why I was confused when they all appread colored. But I will test this again.

**Comment by madprops** [comment]
You probably colored them when they were at the root domain, which saved  the profile at that root.

**Comment by madprops** [comment]
But now it makes me wonder about the profile system. Should I keep using profiles, or should I allow just temporary edit of tabs...

**Comment by N3C2L** [comment]
Hm, do you think it's possible to create persistent profiles for a single tab which are independent from the urls/domains of other tabs?

**Comment by madprops** [comment]
I did some experiments, in the end decided to stick with the current profile system.

**Comment by N3C2L** [comment]
Good, it is ok how it is.

**Comment by madprops** [comment]
However, I added `Tab Color` commands. For example `Tab Purple`. This assigns a color to a tab no matter the url. They get resetted at startup.

**Comment by N3C2L** [comment]
Sounds useful, thanks.

**Comment by N3C2L** [comment]
I would be happy if you can implement an option to have the "Exact" checkbox (Match exact URL) in the profile editor enabled as a default setting when editing tabs.

Thoughts for seperate match exact URL profiles (maybe a checkmark setting):
When a profiles is edited, it gets an internal timestamp. To differentiate from other profiles that have other timestamps. And if profiles overlap with the same exact URL and internal timestamp, the internal timestamp counts one second forward.

**Comment by madprops** [comment]
I can add the default exact setting, on `More` probably. But I don't understand the second part, how would the timestamps be used? Right now profiles are unique by URL, two profiles can't have the same URL.

**Comment by N3C2L** [comment]
When a profile is edited it has a unique URL and a unique timestamp (the time when a change to a tab has been made to become the status "edited"). And a second profile with the same URL but another timestamp is created when a tab gets edited at another time.

**Comment by madprops** [comment]
And how would tabs get associated with the profiles, would it be persistent?

**Comment by madprops** [comment]
Anything I add to a tab item is going to be temporary except the tab's id. Each tab has an id. The id persists as long as the tab exists. So though I'm not fully understanding what you are saying with the timestamps, I think the proper approach would be to have urls in the form of `id:1234` which would match the specific tab. Which I tried the other day, it made the code more complex. Is this kinda what you mean, a profile that is attached to a tab for the remaining of the tab's lifetime?

**Comment by madprops** [comment]
New setting in `More`. This will default  exact when creating new profiles.

![exctprof](https://github.com/madprops/grasshopper/assets/206498/e31eec43-1026-49b1-9e87-abbb017c2acc)

**Comment by N3C2L** [comment]
Ok, thanks. Maybe another approach:
Checkbox in the "edit profile" menu that contains "Match exact tab id only" and option to make it enabled by default. That would solve my problem even more that tabs with the same URL get colored together by accident. Question here is: Is the tab id persistent through browser restarts?

**Comment by madprops** [comment]
Tab ids change on restarts:

![ids234](https://github.com/madprops/grasshopper/assets/206498/f3bddcb7-ab42-482d-a5e4-dc43f7b19886)

Doesn't the tab color commands solve your issue? like `Tab Red`. They apply to the specific tab which would stick in the sidebar at least.

**Comment by N3C2L** [comment]
Thanks, but I'd have prefered it persistent: A single profile for a single exact URL match. And then a new profile with the same URL. You say that this isn't possible so then I was thinking for another additional thing like unique IDs or timestamps that complement the URL only thing for profiles. But I couldn't explain how that should be added.

**Comment by N3C2L** [comment]
I was thinking like this: When a single tab gets associated the first time with a profile (by editing the single tab), this marks the timestamp/unique ID that they share together. And that timestamp/unique ID can be used to distinguish to other profiles with other ID/timestamps.

**Comment by madprops** [comment]
Timestamps wouldn't be persistent. I can't write to the browser's tabs, they're read-only.  But i'll keep thinking on this.

**Comment by N3C2L** [comment]
Ok, maybe unique IDs that can be persistent when creating profiles?

**Comment by madprops** [comment]
I can make profiles match exact tabs, I did it before, but it's a bit messy.

**Comment by madprops** [comment]
Here are all the properties tabs have: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab

**Comment by N3C2L** [comment]
If it is not persistent, then I don't need match exact tab ids. Then I can use your color tab solution.

**Comment by N3C2L** [comment]
So the URL is the only persistent indicator a tab can have?

**Comment by madprops** [comment]
As far as I know. I'm checking if there's a way to write data to tabs, but I think it's ready only.

**Comment by N3C2L** [comment]
When I edit the tab title in grasshopper it is persistent, I tested it. Maybe if its possible to add a number to the tab titles end, then we could use persistent profiles with same URLs?

**Comment by madprops** [comment]
I was also thinking about matching titles, but in this case it's persistent because it saves the title to a profile, which is matched by the url. The title only exists within grasshopper.

**Comment by madprops** [comment]
By the way, wanted to thank you for the issues you've created here, you have given me interesting ideas to make the extension better.

**Comment by N3C2L** [comment]
Thank you too for taking the time to do this. It's the best tab search / filtering addon out there and I am pleased that I could give you ideas to make it better.

**Comment by N3C2L** [comment]
I tested the coloring tab function in the "sidebery" firefox addon. Maybe you can look in the sourcecode of sidebery, it is here on github. I tested coloring tabs that have the same URL. In sidebery you can colorize tabs differently although they share the same URL. And the color is persistent over browser restart.

**Comment by madprops** [comment]
I see. I might check it out.

**Comment by madprops** [comment]
Oh, looking at the code I found a call to this https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/setTabValue

This seems to allow me to write data to the tabs. I'll try it out.

**Comment by madprops** [comment]
For this to work I'll have to give an explicit ID to the extension. Which I didn't before. This will reset everybody's settings. But I guess it's necessary.

**Comment by N3C2L** [comment]
Glad that you found a solution!

**Comment by madprops** [comment]
I think I'm going to make a `Grasshopper 2` to not cause users trouble with the ID issue.

**Comment by N3C2L** [comment]
Can't help you here. But I would be okay with either.

**Comment by N3C2L** [comment]
Personally I would stick with Grasshopper 1 because settings are quickly reinstated.

**Comment by N3C2L** [comment]
Or you ship both versions in one update with option to switch between them. this way users can look at the settings they had in grasshopper 1 and apply them in grasshopper (beta).

**Comment by N3C2L** [comment]
I think I can close this know, since you introduced the new grasshopper version already which solves this issue.
