### ISSUE TITLE
Resizable Favorite Bar

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#21]
It would be marvelous if we could resize the favorite bar. I would be happy if the  the favorite bar can be reduced to show only the icons of the buttons with just minimal background.

**Comment by madprops** [comment]
What do you mean, it only shows the icons, I don't understand

**Comment by madprops** [comment]
The background of buttons looks bigger on popup than sidebar for some reason. But on my sidebar they look small enough.

**Comment by madprops** [comment]
Sidebar:

![favbawrs234](https://github.com/madprops/grasshopper/assets/206498/c9809387-c61e-46ae-8620-e6e6b0d1e289)

**Comment by N3C2L** [comment]
Ok, thanks. I know now what the problem is: I use a firefox fork called "floorp". And this firefox version has a unique sidebar that is like the sidebar in Vivaldi browser. If loaded grasshopper in this floorp sidebar, the icons appear bigger than in the native sidebox of the firefox (both sidebars can be used together on one site).

**Comment by N3C2L** [comment]
Alright. In Vivaldi you can resize (zoom) the sidebar, but not in Floorp. Maybe Floorp will implement this sooner or later, hopefully.

**Comment by madprops** [comment]
Did you try changing the font size in `General` settings in Grasshopper? It scales the whole thing.

**Comment by N3C2L** [comment]
Thanks, you are right. I have litte bad sight, so I changed the font size to 15. Do you think it is possible to implement another setting that only scales the upper buttons and the favorite bar together, but independently from the font size?

**Comment by madprops** [comment]
On version `1000` there's a new setting in `General` called `Button Size`. This can be used to independently modify the size of buttons. You can try setting a lower value than the font size.

![buttonsize8234](https://github.com/madprops/grasshopper/assets/206498/5338143b-0bff-4e47-bd1b-133a1a886ce6)

**Comment by N3C2L** [comment]
This is very useful and solves my problems, thank you!

**Comment by N3C2L** [comment]
Love the fact that buttons wrap now, so they all fit in the sidebar if the sidebar has reduced with.
