### ISSUE TITLE
Single tab warnings

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#22]
I would be glad if you could implement these warnings, because I don't want to to close them by accident:
Warn when close a single colored tab + warn when close a single tab with a note.
Maybe option for a single tab warning when closing an edited tab generally.

**Comment by madprops** [comment]
Would a general `edited` warn setting be sufficient?

**Comment by madprops** [comment]
Hmm, `warn_on_close_tabs` already has a `special` setting which is the default. I will include this to apply to edited.

**Comment by madprops** [comment]
![special2345](https://github.com/madprops/grasshopper/assets/206498/012d31c1-522c-4564-83b5-f0906b03ca9c)

**Comment by madprops** [comment]
Or maybe i'll change this to be more granular.

**Comment by N3C2L** [comment]
I would be happy with a general edited warn setting, but feel free to add anything else.

**Comment by madprops** [comment]
Decided to simply add the edited check https://github.com/madprops/grasshopper/commit/4fcb2b21fd9d8a6a7a10623928c5c9f3da8eae60

Available in next version.

**Comment by N3C2L** [comment]
Thanks, it's working!
