### ISSUE TITLE
After Action Warnings

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#24]
Sometimes actions are not fulfilled in the grasshopper addon interface. And then you get no closing tab warnings (if they are activated) - e.g. if you close tabs outside the grasshopper interface by the native firefox interface or by other extensions.
And if this happens after action warnings could be useful: If the grasshopper addon recognizes, that a colorized tab got closed outside of the grasshopper interface, a warning popup appears that maybe contains: "A colorized tab was closed. Would you reopen it?". 
The same could be implemented with navigation warnings (to mimic lock tab) like "Change of Url detected, would you go back to the previous Url?". Navigation in a tab is possible with this setting, but the warning does not appear when you open urls in a new tab.

**Comment by madprops** [comment]
No that's complexity Grasshopper shouldn't deal with.

**Comment by N3C2L** [comment]
Alright, thanks anyway.

**Comment by N3C2L** [comment]
Maybe possible to implement if the notifications happen inside the grasshopper addon (like the other warnings in grasshopper) and not outside?

**Comment by N3C2L** [comment]
If I click a link outside grasshopper, the url changes inside a grasshopper tab. And if this url changes inside a tab, a warning should appear inside grasshopper addon that the url has changed + the possibility to switch to the previous url of the this tab.

If I close a tab outside grasshopper, grasshopper recognizes this change, because he closes the tab in the visible list. But when this tab was marked before the close with a close warning thing ( like color on the tab) then grasshopper should popup a warning that a colored tab (edited tab) has closed.

**Comment by madprops** [comment]
I understand. I experimented with this. While I was able to add something like it, for close and url change, the code involved was complex, and it introduced some bug already. I decided to not add this for now. Other extensions can still be used alongside this one to add functionality like that.

**Comment by N3C2L** [comment]
Thank you for testing it. I would be pleased if you find other ways / workarounds / or simliar behavior to implement it. Maybe sometime in the future. I think I can close this for now.
