### ISSUE TITLE
Hover Tab Action Bar

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#27]
Following option would be a great thing:
Hovering over a tab shows commands in the right zone of this hovered tab:
colors, pin, unload.. (other commands)
Commands can be customized.
Buttons reduced like the ones in the favorite bar without titles.
Problems may occur: 1. if the height of a tab is set too small, the hover bar can overlap with other tabs. 2. if the sidebar is too small user could not read the title of the tabs. Hence the hover bar could be set to hidden but to expand horizontally (vertically?) if the mouse hovers over the tab's favicon only.

**Comment by madprops** [comment]
I understand the idea. But I think there's already too many ways to invoke commands.

**Comment by N3C2L** [comment]
Advantage would be here that you don't have to select the tab first when doing commands with the hover bar.

**Comment by madprops** [comment]
I'll do some tests to see if it's easy enough to implement.

**Comment by madprops** [comment]
How about a single button appears on hover, on the right side. And when clicked shows the commands.

**Comment by madprops** [comment]
Maybe reuse the Extra menu for that.

**Comment by N3C2L** [comment]
I would love to see as much as buttons possible when hovering over a tab (if that can be an option I would be happy).

**Comment by madprops** [comment]
I implemented a Hover Button, activated in `Show` settings. I didn't like the idea of drawing a bunch of cmd buttons per tab, and the single button works well enough. It can be placed at right or left side. What it does when clicked is show the Extra menu, which makes sense since the Extra menu is meant to be applied on items as well. I think it works well. Also the close button (x) is not shown if the hover button is on the same side. The close button can also be placed left or right.

**Comment by madprops** [comment]
I'm making it have its own menu `Hover Menu` on version `2005`.

**Comment by madprops** [comment]
I'm making it have its own menu `Hover Menu` on version `2005`, instead of using `Extra`.

**Comment by N3C2L** [comment]
Thanks. I'm fine with that button. I have it on the left side.
Just a little problem now: I used the favicons to select items, you named it "Item Pick". Solution could be: Activate "Item Pick" with a right click on the this new hover button.

**Comment by madprops** [comment]
Right click pick added in `v2006`. Plus added a setting in `Auxclick` to assign a command to middle click on hover button, which defaults to `Close Tabs`. Also right click on hover button can be disabled on `More` if you want the context menu instead.

**Comment by N3C2L** [comment]
Thanks a lot!
