### ISSUE TITLE
filter edited

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#28]
Hey,
Found a bug: "Filter edited" command is missing from the command list. I would be glad if you can add them, because in the main buttons above the command is there under "edited".

**Comment by madprops** [comment]
I actually just removed Edited. Decided to add `Titled` instead. There's also a command for Titled. So now there's filters for Colors and Titles. Like `Filter All Colors` and `Filter Titled`. I guess I'll add a `Filter Edited` command anyway.

**Comment by N3C2L** [comment]
Thanks, a `Filter Edited` command would be great to have, because I like the list with both colored and changed titled tabs.

**Comment by madprops** [comment]
This is now added in `v2010`.
