### ISSUE TITLE
undo command

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#29]
I know I did a lot of requests lately and please take all the time in the world you need for my requests, but I would seriously need a command: "Undo Edited" for latest edited tabs. Because often a tab already has a color, and sometimes I accidentally remove the color by apply the same color again (so the tab got no color then and is removed from the "All colors" list). But you could also change the behavior to this: If a color is applied on a tab, don't remove the color if the same color is applied again.

**Comment by madprops** [comment]
Ok I guess the toggle color thing can be a problem. I can just make it not toggle. I'll a add a setting but make it not toggled by default.

**Comment by N3C2L** [comment]
Thanks, great.

**Comment by madprops** [comment]
This is now added in `v2010`.
