### ISSUE TITLE
Customizable context menu

### ISSUE THREAD

**Issue by ghost-of-freedom** [madprops/grasshopper#3]
Would it be possible to add an option to modify the entries in the right-click context menu? It would be great if there was a way to have any combination of the commands listed under Tabs -> Cmd... in the context menu (with submenus it would be even better, but maybe that's asking too much). If the scope of all Cmd... commands is too broad, maybe the right-click menu for tabs could be customized to have any of the commands affecting a single tab, and right-clicking the empty space could bring up a different menu that can be customized to have any of the other commands?

**Comment by ghost-of-freedom** [comment]
I just saw you add that you decided not to implement this to your message. I'm alright with that, but I spent a good while writing the post below, so I decided to post it. Maybe it will be of some help, if you decide one day that you'd like to implement this after all. I think this issue can be closed now, I would like to thank you for taking it into consideration, and please keep up the good work.

Original reply below this line:
------------------------------------------------------- 

I think that text based configuration is a solid start; the GUI tool could be added later, that creates and applies the text configuration under the hood. But I'm no expert.

If you do not plan to attach a GUI eventually, it would probably be a good idea to put a big, scary warning about it being advanced configuration; otherwise, I'm afraid some casual users are bound to make a mess in the editor, and then get angry when things don't work (an obvious reset button to click in such case would probably help). I do think that GUI configuration is more convenient, but as long as the functionality is exposed, the people that really care will make do.

It does sound like there would be quite a bit of work involved with the way the extension is designed though; I can't offer much in the way of advice, but maybe it would be easier to decide what to do after seeing an example implementation? [sidebery](https://github.com/mbnuqw/sidebery/blob/358bcaf0218c624e22d4eac4d7aba9e6efd1cc86/src/page.setup/components/menu-editor.vue) extension has this functionality implemented, it might give you an idea of the amount of work required, and help you decide if it's something you are willing to undertake.

As for adding new features, I don't think it needs to be automatically added into the menu - in my opinion it's enough if they are marked as new in the configuration area (since even if you only have text configuration with an editor, I imagine you'd still want to have a list of possible functions and other help to the side). That is unless you plan to remove some functions that can be used in the context menu; but that's a problem that comes with exposing API in general, and it's always a pain.

**Comment by madprops** [comment]
Ended up adding something though, called Extra Menu.

If it is not empty, it will add an `Extra` entry in the item menus.

This can be configured in the Show section of settings.

![extramenu6](https://github.com/madprops/grasshopper/assets/206498/e2b47e79-6e33-4e4c-84ab-478a4a3090d8)

![extramenu4](https://github.com/madprops/grasshopper/assets/206498/6b9bfac8-4ae0-484c-9bdc-b3fe52dfacf8)

![extramenu5](https://github.com/madprops/grasshopper/assets/206498/cc44736b-a7ae-4650-af14-72c1b5ea0b46)
