### ISSUE TITLE
button size

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#31]
When button size is set to 1, there is a border visible inside the favicons of the favorite bar. I would be grateful if you can remove this. 
![border](https://github.com/madprops/grasshopper/assets/74585843/a510d31b-7942-47b4-ab02-3f322453caab)

**Comment by madprops** [comment]
Maybe I'll remove the buttons backgound+outline altogether from the favorites bar.

**Comment by madprops** [comment]
Yeah it looks good with only the icons.

**Comment by madprops** [comment]
I'm going to remove the button size setting since it complicates a bit the styling, and it's probably not necessary now. The buttons in general got a bit smaller.

**Comment by N3C2L** [comment]
That's perfect, thanks.

**Comment by madprops** [comment]
This is now live in `v2017`.

**Comment by N3C2L** [comment]
Thanks!
