### ISSUE TITLE
warning inside firefox

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#32]
If you switch to about:debugging#/runtime/this-firefox there is a warning if you scroll to grasshopper. It may concern you:
"Reading manifest: Warning processing sidebar_action.browser_style: "browser_style:true" has been deprecated in Manifest Version 3 and will be unsupported in the near future. While "sidebar_action.browser_style" was not explicitly specified in manifest.json, its default value was true. The default value of "sidebar_action.browser_style" has changed from true to false in Manifest Version 3."

**Comment by madprops** [comment]
Thanks. Doesn't seem to be from something I do, I don't define `browser_style` in the manifest. Seems to be a general warning. But I'll keep it in mind, thanks.
