### ISSUE TITLE
Export Settings

### ISSUE THREAD

**Issue by daffydock** [madprops/grasshopper#37]
Hi, 
Just recently found your awesome, yet very light on resources add-on. Love how quick it is. I am going to be putting it on a few machines and was wondering, in cased I didn't see it, if there was an Export option, or for that matter where the settings are saved on the PC. So I can copy/paste the file over if necessary.  

I can look for it myself but thought it wiser to ask the Dev first, in case I missed anything.

**Comment by madprops** [comment]
Hi. There is a way within Grasshopper to expose settings data.
Go to Settings. In the top there's a menu button in the middle.
Click the button then -> Data -> Export.
You can save this text and Import it on other machines by using the Data menu as well.

**Comment by daffydock** [comment]
Ah, excellent. Totally Missed it. I will close this one as well.
