### ISSUE TITLE
Support For Container Tabs

### ISSUE THREAD

**Issue by daffydock** [madprops/grasshopper#38]
Was wondering if support for Container tabs, that is to say some way to be able to tell different containers being used for the same/any tabs/site was something that you would be looking into incorporating into Grasshopper. 

I can tell the different containers being used in the omni bar, however in there a way to be able to tell by overview by simply looking at the sidebar? 

Would that be possible? If not, that is fine. 
Thank you, either way.

**Comment by madprops** [comment]
I have no plans to add container support, I never use that feature personally.
If I find that tabs expose this information easily I wouldn't mind it but it seems it needs a new permission and API (contextualIdentities).
But i'll keep it in mind and check if it's easy enough to add.

**Comment by daffydock** [comment]
Then absolutely no worries. 
Thanks for keeping it in mind, either way.
I will close.

**Comment by madprops** [comment]
Hi @daffydock - there is now some support for containers in Grasshopper. It now shows icons representing the tabs' container. The icon can be clicked to filter/show other tabs in the same container. Tabs can be opened in a specific container. Apart from that not much else, for the rest of the functionality there is the official extension by firefox to manage containers.
