### ISSUE TITLE
Help: Move auto hiding side bar to the right. 

### ISSUE THREAD

**Issue by daffydock** [madprops/grasshopper#39]
Hi. 

I am attempting to set Grasshopper in a way that best works for my workflow. One of the main issues I have found was the lack of an Auto Hide via hover feature for the side bar. Now, this can be done with CSS. So far, I made it fit the correct size for my needs and it auto hides when not being hovered on. 

This is how my setup looks right now on my test machine.  

![image](https://github.com/madprops/grasshopper/assets/32020577/c8bd8bdb-942e-47d3-8ed9-cf16db40827b)

Below is the code. Admittedly, this is FrankenCode I clobbered together via different sources. I take no credit and I have next to 0 know-how of what I am doing. I was hoping to see if you may be able to help me to move the Grasshopper side bar over to the right hand side. 

Currently it is on the Left hand side and I am not sure how to move it over. Some people may prefer this, and maybe they may find this particular setup useful but I much prefer it on the right. 

I am aware this might not be the use case for most people but perhaps someone might find at least some of the CSS useful. Since I was not able to find an exact fix when I looked for it. 

Any help would be appreciated. I am also looking at some other CSS here on Github to see if I can find a fix on my own but so far no luck.

The only thing I have found was this but it does not provide the correct outcome when I tried it. Clearly, I am missing something:

/* For right sidebar change 'margin-right' to 'margin-left' */
#sidebar-box:hover {
  margin-left: calc((var(--wide-tab-width) - var(--thin-tab-width))*-1)!important;
}

----
Code Below
----

/* Grasshoppers Original CSS  
}
*/

#TabsToolbar {
visibility: collapse !important;
}

#sidebar-header {
display: none !important;
}

#sidebar-search-container {
display: none !important;
}

#sidebar-splitter {
width: 2px !important;
}

/* Position of window controls*/
#TabsToolbar .titlebar-buttonbox-container {
display: block;
position: absolute;
visibility: visible;
}

/* Reposition the close/maximize/minimize buttons for the "normal" toolbar density /
 */
:root:not([uidensity]) #TabsToolbar .titlebar-buttonbox-container {
margin-left: 3px;
margin-top: 3px;
}

/* Alternative -- Reposition the close/maximize/minimize buttons for "compact" toolbar density */
:root[uidensity="compact"] #TabsToolbar .titlebar-buttonbox-container {
margin-left: 3px;
margin-top: 3px;
}

/* Sidebar Settings below. Change as needed depending on your set up. Help Please  
}
*/

#sidebar-box {
  background-color: #2B2A33;
  overflow: hidden;
  height: calc(50% + 6px);
  position: fixed;
  max-width: 26em !important;
  width: 50% !important;
  display: block;
  transition: 90ms;
}

#sidebar-box:hover {
  padding-bottom: 0px;
  position: absolute;
  z-index: 1;
}

#sidebar-header {
  background-color: #2B2A33;
}

#sidebar {
  width: calc(45px * 7) !important;
  max-width: 50vw !important;
  height: 100%;
}

#sidebar:hover {
  max-width: 100% !important;
}

#appcontent {
  margin-left: 1px;
}

**Comment by madprops** [comment]
No idea.. but there's this button to move it to the right it seems:

![sidebar245](https://github.com/madprops/grasshopper/assets/206498/09c751ba-5405-4fe1-b551-2fd06bab97f9)

**Comment by daffydock** [comment]
Thanks. 
Yeah, I had tried that. 
You may notice activating that option does not do the expected result. I assume due to the CSS.

**Comment by daffydock** [comment]
Updating: 

Okay, so while playing around with CSS and frankencoding some more during the weekend, I was able to switch it over to the right hand side. It is not exactly what I had before but it works, it hovers in and out and it is enough for my needs. 

Thanks for the help, anyway. 
Also, wanted to say that the rate at which you update the app is quite something. 

I will close this issue. 
Cheers.
