### ISSUE TITLE
Keyboard shortcuts ?

### ISSUE THREAD

**Issue by u2615** [madprops/grasshopper#4]
Loving the extension so far, but is there a way to customize keyboard shortcuts I'm not aware of ?
I rely heavily on keyboard while browsing, not using the mouse so much, and I'd find very convenient if there was a way to pick, edit, close etc tabs without using the mouse.

I'm currently using the command palette but it feels a bit weird having to open the command palette, searching for close, selecting the right action with arrow keys, just to close a tab from the keyboard.

**Comment by madprops** [comment]
There's some keyboard shortcuts, they should all be documented in the About window. For instance you can use the Delete key to close selected tabs. Customizable keyboard shortcuts is something to consider, I'll think about it.

**Comment by madprops** [comment]
Think I'm gonna make it so you can specify modifiers per shortcut.

**Comment by madprops** [comment]
Next version:

![ghkb49](https://github.com/madprops/grasshopper/assets/206498/a4eb7c85-3b13-48d1-9b10-c65a5f9b6bfb)
