### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#40]
When users try Grasshopper for the first time, they may be confused that the following keys are remapped:

Shift+Home/End selects towards edges.
Ctrl+Arrow + left/right toggles menus (main menu, actions menu).

Because in the search bar when typing these functions miss then:

Shift+Home (highlighting all text to the left)
Shift+End (highlighting all text to the right)
Ctrl+Arrow left (Move one word to the left)
Ctrl+Arrow right (Move one word to the right)

So new users can't use shift+home/end to highlight and erase text quickly, or move one word left or right with ctrl+arrow keys in the search bar. It may be useful to enable these keys by default.

**Comment by madprops** [comment]
Ok thanks, I'll consider removing these mappings.

**Comment by madprops** [comment]
What I did is make it work like other similar mappings where it conflicts with the filter: If the filter is focused then ignore.

**Comment by N3C2L** [comment]
Alright, thanks. Is there a shortcut to jump between the filter focus and the tab list focus?

**Comment by madprops** [comment]
I see. Tab is already used to cycle between modes ... what I'll do is focus list on Esc, if filter is empty. How about that?

**Comment by N3C2L** [comment]
Yes, that's good. Thanks.

**Comment by N3C2L** [comment]
Question: Are the arrow up / down keys to select tabs working on your side?

**Comment by madprops** [comment]
Yes. What's wrong?

**Comment by N3C2L** [comment]
Imagine a file browser. In a file browser you can press arrow up/down to select the files. I was thinking that this behavior was working in your addon. Procedure if implemented: Search for something, then press the arrow down key to switch through the tab list and select a tab with enter.

**Comment by madprops** [comment]
I'm confused. I can filter something, then press down arrow to select an item, then press enter. Or without filtering. Not sure why it isn't working for you. Can even select multiple by holding Shift.

**Comment by N3C2L** [comment]
If you use a file browser and press arrow up/down the file gets highlighted first, and if you press enter then the file is executed. On my side the tabs in grasshopper don't get highlighted first when I am pressing arrow up/down. They get only highlighted when I am holding Shift+Arrow keys

**Comment by madprops** [comment]
Something is different about your browser then. On my end I can hit down arrow normally to highlight items below. It works as you describe. You use Floorp right?

**Comment by N3C2L** [comment]
Yes, maybe it's different in another firefox, I will test.

**Comment by N3C2L** [comment]
Sorry! It is working in another firefox. I know what the problem was: I changed the highlighted color with CSS and it wasn't visible, I changed that know. Sorry again for the confusion.

**Comment by madprops** [comment]
Oh haha. I just tried it in Floorp and it indeed worked. Ok no problem.

**Comment by N3C2L** [comment]
Yes, try in Floorp two grasshoppers side by side, its funny! because you can have two sidebars there.

**Comment by N3C2L** [comment]
one filter here, other filter other grasshopper.

**Comment by madprops** [comment]
Nice.

**Comment by N3C2L** [comment]
Hmm. It was not the CSS.
If you deactivate the scroller widget you can't highlight the tabs with the arrow keys.

**Comment by madprops** [comment]
My bad, i'll upload fix soon.

**Comment by madprops** [comment]
This is now fixed.

**Comment by N3C2L** [comment]
Thanks a lot for the fix!
