### ISSUE TITLE
Show Settings cmd

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#41]
Right now the "Show Settings" command takes you directly to the "General" settings. But I have "direct settings" disabled. The command should spawn the category menu instead, or is this only when clicking the button "Settings"?

**Comment by madprops** [comment]
A menu with the categories should appear instead yeah.

**Comment by N3C2L** [comment]
Ok, thanks. If you put the "Show Settings" cmd in the favorite bar and run it, the category isn't appearing.

**Comment by madprops** [comment]
It's not there yet. I will upload soon

**Comment by N3C2L** [comment]
Thanks.

**Comment by N3C2L** [comment]
It's working now. The category is appearing, but if this "show settings" cmd is run from favorite bar the menu is not entirely visible. It would be glad if you could center it to the middle of the interface.

**Comment by madprops** [comment]
Oh hmm, that's a bug. I'll fix it.

**Comment by N3C2L** [comment]
Thanks, it's the same when the this cmd is executed from the palette.

**Comment by madprops** [comment]
Yeah I was calculating `y` coordinates wrong in the context component. Upload soon.

**Comment by madprops** [comment]
Should be fixed now. It should act normally now, and if here's not enough space it shows a scrollbar.

**Comment by N3C2L** [comment]
Yes, having the menus appear directly under the favorites is very useful and so is the scrollbar, thanks.
