### ISSUE TITLE
Where are notes?

### ISSUE THREAD

**Issue by lifehaschanged** [madprops/grasshopper#42]
Hi,

i have grasshopper installed but not activated last month.
It was possible to take notes back then.
When we can add notes again?

**Comment by madprops** [comment]
Hi. Notes were removed when I removed the profiles system. Not sure I want to add them back ... in what way do you use these?

**Comment by madprops** [comment]
I'm adding them back in some way, working on it.

**Comment by madprops** [comment]
There's notes again. You can right click items and select `Notes` or use the `Edit Notes` command.
Items with notes show a notepad icon on the left, which can be clicked to view notes.
