### ISSUE TITLE
Ctrl Key

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#46]
When the ctrl key is pressed too long, the palette appear. But in the "about" page it is written that only on double tap of the ctrl key the palette should appear. You can't press shortcuts with the ctrl key if this key triggers the palette before.

**Comment by madprops** [comment]
Seems you browser might be repeating the keydown, which doesn't happen in mine. But I added an e.repeat check to ignore repeating keydowns, this might fix it. On next version.

**Comment by N3C2L** [comment]
Thanks, it's solved.
