### ISSUE TITLE
Middle Click

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#47]
Since last update the middle click to close tabs doesn't work anymore.
Another question: what is smooth scroll and where you can see it in action in your addon?
That must be something different than autoscroll which gets activated now if you middle click on tabs.

**Comment by madprops** [comment]
Bunch of stuff broke with the alt action thing. I decided to remove that.
The smooth scroll happens in certain actions. Like when you use the Step Back button, it scrolls to an item smoothly. It's not the auto-scroll thing.

**Comment by N3C2L** [comment]
Thanks, the middle click to close tabs shortcut is working again. But maybe this is again only on my browser: If you close a tab with middle click and then move the mouse up and down, the tab list scrolls as if autoscroll is activated?

**Comment by madprops** [comment]
Is this a recent thing? My operating system doesn't have that autoscroll thing so I can't test. Or has this always happened?

**Comment by N3C2L** [comment]
It was also before the update. Hm, did you test it on both, sidebar and popup? Because on sidebar the autoscroll icon is visible and on sidebar not if a button is closed with the middle click mouse button. Or maybe you haven't autoscroll enabled in firefox settings?

**Comment by madprops** [comment]
I could enable autoscroll, and saw the issue, yes.
This seems to fix it:

```js
  DOM.ev(window, `mousedown`, (e) => {
    if (e.button === 1) {
      e.preventDefault()
    }
  })
```

On v2046 soon.

**Comment by N3C2L** [comment]
Much obliged.
