### ISSUE TITLE
Unloaded tabs recovered by tab session manager doesn't show up

### ISSUE THREAD

**Issue by sunng87** [madprops/grasshopper#5]
I'm using Tab Session Manager to restore tabs between browser sessions. It seems to have an issue with Grasshopper that those unloaded tabs are not displayed in sidebar until I switch to Tree Style Tab and back again.

**Comment by madprops** [comment]
How many tabs? I'll try Tab Session Manager and see if it happens to me.

**Comment by sunng87** [comment]
![image](https://github.com/madprops/grasshopper/assets/221942/d687ab10-f02f-4199-bf8a-454a07d4631d)

Only pinned and active tabs are shown up. Those unloaded ones are not visible. But once it becomes active, it's displayed in Grasshopper

**Comment by madprops** [comment]
First thing I'm noticing is that when I open a session, something closes the sidebar in the process. When I bring the sidebar back all tabs are there. This is with 22 tabs. Does your sidebar closes to? I'll try more variations.

**Comment by sunng87** [comment]
Yes, I'm Linux/Sway and I can see that Tab Session Manager recreates the window to restore its tabs.

**Comment by madprops** [comment]
Ok I can reproduce this when I open on the same window.

**Comment by madprops** [comment]
I found the issue. An event that listened to onCreated was missing. I added it and now it works. This will be available in the next version in a few hours.

**Comment by sunng87** [comment]
I confirm this has been fixed. Thanks for super fast response and this great addon!
