### ISSUE TITLE
colors gone

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#56]
Why did you remove some colors? Is it because the palette with the cmds is then too crowded? If that's the case than maybe an option for an "extended palette" or "color palette" could make sense. If activated in the settings, more color options could appear in the palette. Maybe in a new settings category like "palette" users could activate/deactivate categories/cmds which should appear in the palette.

**Comment by madprops** [comment]
I removed orange and purple, because they would get confused with the core colors like yellow. I didn't find them necessary.

**Comment by N3C2L** [comment]
Ok, thanks. I think you are right. The colors looked indeed to similar.
But maybe another solution for the users as a compensation:
Priority symbols. If a tab has a priority symbol  (for example an exklamation mark) with maybe 3 different options to choose from: min, normal, max to choose from. This hierarchy symbol would not lead to confusion with the colors and I would be glad if you could implement them.

**Comment by N3C2L** [comment]
Sorry about posting my ideas here in the issue section again. I think I can close this and add the ideas as seperate posts in the idea section.
