### ISSUE TITLE
tabs to bookmarks bar

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#59]
I found a bug:
If you drag and drop a tab from the native firefox tab bar into the firefox bookmark bar, the title of the tab will be used for the stored bookmark item.
If you drag and drop a tab from the grasshopper sidebar to the firefox bookmark bar on top, then the bookmarked item in the bookmark bar rename themselves into the url instead of keeping the title.
The tab inside the grasshopper sidebar also gets renamed to the url when bookmarked this way. The tab doesn't get renamed if the the tab is drag and dropped from the grasshopper popup Interface though. 

But another problem occur if you want to drag and drop a tab into the firefox bookmark bar: If you are inside the grasshopper sidebar and want to drag and drop a tab straight above into the bookmark bar of firefox, then you accidentally move the tab inside the grasshopper interface (but that's not what you want, because you just wanted to move the tab into the firefox bookmark bar, and not moving the tab inside the grasshopper interface).

A solution could be that a dragged tab inside the grasshopper interface moves only when you release the mouse button, but doesn't move if you just hold the mouse button. A visual indicator (an arrow or a line between tabs) where the tabs then appear if the mouse button is released could be useful.

**Comment by madprops** [comment]
I didn't know it was possible to drag from grasshopper to other firefox components. Not sure I can do anything about the title vs url. I tried changing the text data to the title and it won't drop into the bookmarks bar, it needs to be the url to work for some reason. 

Also I don't like the idea of not re-ordering the tabs instantly:

What I did is also enable dragging when using the `Lock Drag` setting. If you have this on, you will only re-order tabs when holding Ctrl key. You can use this to drag to the bookmark bar without messing your tabs by dragging without holding Ctrl.

This is on `v2101`.

Thanks.

**Comment by N3C2L** [comment]
Thanks. Maybe you can research the solution for keeping the titles in the bookmarks in the tree style tab addon, because it's working there: https://github.com/piroor/treestyletab
https://addons.mozilla.org/de/firefox/addon/tree-style-tab/

**Comment by madprops** [comment]
Not sure what they do, can't find anything
https://support.mozilla.org/en-US/questions/1411173

**Comment by madprops** [comment]
This is now fixed. The code in that project was helpful.

**Comment by madprops** [comment]
I'll take a look tomorrow.

**Comment by N3C2L** [comment]
Thanks!

**Comment by madprops** [comment]
It should work now. 

```js
        if (item.url) {
          urls.push(item.url)

          if (item.title) {
            moz_urls.push(`${item.url}\n${item.title}`)
          }
        }
```

```js
  if (moz_urls.length) {
    e.dataTransfer.setData(`text/x-moz-url`, moz_urls.join(`\r\n`))
  }

  if (urls.length) {
    let uri_list = urls.join(`\r\n`)
    e.dataTransfer.setData(`text/uri-list`, uri_list)
    e.dataTransfer.setData(`text/plain`, uri_list)
  }
```

Also fixed some other stuff. 

And added icon settings for the close button and hover button.

**Comment by N3C2L** [comment]
Works flawless, thanks!
