### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by arjpar** [madprops/grasshopper#6]
I have a few questions:
1. Can/should this extension be used in conjunction with Simple Tab Groups? I know Grasshopper has the ability to add tags to tabs but I don't see it as a full on replacement for tab groups.
2. It would be useful to update the README to provide a description of the extension.
Great work!

**Comment by madprops** [comment]
I tried installing STG and it flickered my screen with some kind of bad glitch, so I removed it immediately. There is no interoperability whatsoever with STG. In the future if mozilla adds  tags/groups to tabs natively I might use those.
