### ISSUE TITLE
glow setting

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#60]
On a dark theme the "glow" settings is looking good, but on a light theme it's gray and makes the text hard to read. I have the hover effect set to "underline", so hovered tabs will be underlined. However the tags are underlined by default which I like and don't want to change. But the tags "glow" when hovered, with no setting do deactivate that glow for tags. I would appreciate such a setting.The same problem appear in the tab box: The glow effect is looking good on a dark theme, but hard to read on a light theme. I really would like to be able to choose the hover effects for the tab box.

I am from Europe, timezone UTC+1, so I am not here to reply the next hours, but I want to thank you again for this great addon.

**Comment by madprops** [comment]
I see. I don't want to add more setting for this. What I'm going to do is remove the glow effect from tags, which is not necessary since they get a double-underline effect. And I'm going to change the hover effect on the tab box to bold instead of glow.

**Comment by N3C2L** [comment]
Thanks for adding these settings,
and thanks for the great alternative mode in the favorite bar (middle click actions).
