### ISSUE TITLE
tab box on popup

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#61]
The tab box doesn't save recent tabs when popup is closed and opened again.

**Comment by N3C2L** [comment]
found another bug in the tab box (same bug in the sidebar and in the popup):
how to reproduce: activate some random tabs until some titles are visible in the tab box. Then navigate to about:addons. Problem then: the tabs in the tab box are gone.

**Comment by madprops** [comment]
This is now fixed.
