### ISSUE TITLE
New feature explanations

### ISSUE THREAD

**Issue by fireworksordie** [madprops/grasshopper#66]
Looks like upon opening a new tab from a link they now are highlighted and have a red circle next to them. Best I can tell the red circle means a not-yet-viewed tab, but I'm not sure what the highlighting means?

**Comment by madprops** [comment]
My advice is to update to have the latest version: `v2124`.
There was some work done to treat certain tabs in a special way so they can act as a header.
So you can for instance have it on top of some tabs, as a title. 
They're called a Header.  It does it automatically. Or through commands.
It used to use `about:blank` tabs. Now it uses `about:newtab` tabs.
So every time you open a new tab it becomes a header, until it turns into something else.
You can disable this feature altogether by unchecking `Enabled Headers` in General settings.
The feature got a bit of a rough start, but it should work ok by now.
