### ISSUE TITLE
double keys

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#68]
I was wondering why the grasshopper interface reacts weird when the modifier keys (ctrl or shift) were pressed one after another. Then I navigated to the triggers setting and found the problem:

I have a trigger set for double shift key > next mode. But cmd also gets triggered if you press ctrl 1x time before and then press shift 1x time one after another. But also vice versa, pressing first shift, then ctrl: this triggers the assigned shortcut for the double ctrl key (if mapped in the triggers setting).

**Comment by madprops** [comment]
Bug is fixed now, thanks.
