### ISSUE TITLE
shortcuts

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#73]
At least on my device I discovered this bug, which affects the internal shortcuts of grasshopper (the ones in the about page of grasshopper), the trigger double keys and the custom shortcuts in the trigger settings.

How to reproduce:
1. click on an unloaded tab that has a non internal website like wikipedia.org
2. when the website has loaded, a shortcut (for example ctrl+up) is not working on this tab
3. You need to click the tab again to make the shortcut above to work.

The problem is, that it's focusing the website after the tab was clicked.
This is maybe good for the grasshopper popup when closed after a tab was clicked but not for the grasshopper sidebar which is permanent open.

**Comment by madprops** [comment]
I know what you mean but It would be more weird if clicking a tab didn't focus the tab. When you click on a tab you expect to start using it right away (?)

Also not sure I can detect if I'm running in sidebar or popup mode, but i'll check.

**Comment by N3C2L** [comment]
Yes, it's true. When clicking the tab it should focus the tab. 
But after clicking the tab it should refocus the grasshopper interface so the grasshopper shortcuts are working again and not the internal firefox shortcuts get the focus. That could be a setting.
I don't know how that can be done. Maybe refreshing the interface? Simulating another mouse click or shortcut that doesn't click, just focus the sidebar again? Or the interface detects if the mouse cursor is still in the sidebar or outside?

**Comment by madprops** [comment]
I don't think the sidebar can be focused.

**Comment by madprops** [comment]
Doesn't seem to be possible.

**Comment by N3C2L** [comment]
You could code a double click: First click on tab activates the tab, second click get the focus back to the grasshopper interface. Only the double trigger click feature is then not available anymore, but shortcuts would work again when a tab is clicked.

**Comment by madprops** [comment]
I already tried simulating a click on the main menu. It triggers the menu but the extension/sidebar gets no focus.

**Comment by N3C2L** [comment]
No, I don't mean just simulating the click. If a user click on a tab, a double click is executed: first tab selects the tab, second click gets the focus back to grasshopper interface.

**Comment by madprops** [comment]
Can't simulate a double click, just single clicks, afaik

**Comment by N3C2L** [comment]
The second click would be activating the tab again (because the mouse cursor is on the tab) and that's bringing focus to the grasshopper interface again.

**Comment by madprops** [comment]
Naturally but I don't think a click can be executed like that, unless you double click it yourself

**Comment by madprops** [comment]
I'm waiting for a reply from the firefox devs, if I get a response i'll update here.

**Comment by N3C2L** [comment]
Alright. I just googled a bit. It was a bug, and some user comment below that this is still a bug and not resolved: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1402227

**Comment by N3C2L** [comment]
But of course this was 6 years ago.

**Comment by N3C2L** [comment]
I was searching again and you might find this interesting:
https://bugzilla.mozilla.org/show_bug.cgi?id=1502713

**Comment by N3C2L** [comment]
Perhaps it's because the shortcuts are not added for mapping in the firefox about:addons interface. If shortcuts from grasshopper added there, maybe you wouldn't need to click the tab again to make the shortcut work. Would you mind to test this with some of your shortcuts? Of course it should be shortcuts that are not used by firefox itself.

**Comment by N3C2L** [comment]
Ok, this is working in another extension: https://github.com/mbnuqw/sidebery
This extension has added it's keys into the about:addons interface.
When you load an unloaded tab in this sidebery sidebar, you can then execute a shortcut without clicking the tab again (for example I tested it with close tab shortcut, mapped to alt+x there).

**Comment by madprops** [comment]
I'll reopen if I get a reply from mozilla

**Comment by N3C2L** [comment]
Hi @madprops 

I don't know if it's now possible to focus the grasshopper sidebar for the hotkeys to be triggered when outside the grasshopper interface.
But I am thinking of a workaround for this issue:
In the about:addons page you added a shortcut to the grasshopper addon:
"Toggle the popup". 
The advantage with this is, that you can press this popup key and then execute every cmd which was already bound to keyboard hotkeys inside the grasshopper interface.
A workaround here would be by adding a new setting, something like "open the grasshopper popup before every shortcut execution".
I'd totally love such an addition and it would resolve the issue for me. Why? Because another click inside the sidebar before a grasshopper keyboard shortcut execution is not necessary anymore. I could execute every grasshopper cmd by hotkeys even when the grasshopper sidebar is not focused (e.g. when a website is focused).

**Comment by madprops** [comment]
Hmm. Should these open a new popup and do that, or should it control the opened sidebar?

**Comment by madprops** [comment]
New browser settings category:

![browsercompas](https://github.com/user-attachments/assets/9f555dc7-293b-4616-84a3-a3fc117cd4ef)

**Comment by N3C2L** [comment]
That's fantastic! Thank you! 

I will certainly add some shortcuts there, for example my 9 would be: 

recent backward/forward jump commands  
loaded tabs filtering  
header tabs up/down  
edit title  
copy/paste tabs  
unload

**Comment by madprops** [comment]
They're 10 commands now.

Also new command that simply triggers an Esc key to close stuff etc:

![esckeytyr](https://github.com/user-attachments/assets/52d1ae7d-64d9-4a68-8f86-bbbbaeb7d795)

**Comment by N3C2L** [comment]
Nice! Of course very useful for menus navigation.
