### ISSUE TITLE
Colour on Domain Rules 

### ISSUE THREAD

**Issue by daffydock** [madprops/grasshopper#75]
Hi, 

There may be a bug, not sure. Perhaps I am doing something incorrectly. 
Simply go to Domain Rules under "General," and create a New Rule. 
In my case, example domain: *github.com* 
Set colour to say, *green* 
Leaving "Exact" checked or not, makes no difference in my testing, for the above. 
Press, *SAVE*

Open new tab, pointing to site. Github loads and opens. Colour remains unchanged from standard setting. 
Tried this with other sites, and results were sporadic. On some, the colour would change but not in all cases. Or if it did, and I switched tabs, the colour would revert to standard setting and in others, like github.com it would not change, at all. In fact, I am looking at the tab right now, as I write this, and it never changed. Worth noting that I have a specific colour that colours the active tab and wonder if that would somehow clash with this settings. Granted, I do not know if that is the case. 

The settings that sometimes took where the split options as well. But only sometimes. The colour one, however is more touch and go. 

I am writing format of sites as github.com or google.com

**Comment by madprops** [comment]
I added a rule for `github.com` and it works in this current url. Are you sure the urls in question start with `github.com` ? Something like `stuff.github.com` would make it fail.

**Comment by daffydock** [comment]
Would not use _Exact_ because obviously it would fail. 
Using _Github.com_

You mentioned a bug, that is great since I am certain that you will address it. Just so show the bug, please see rule here:
![image](https://github.com/madprops/grasshopper/assets/32020577/b099dfef-f53e-4da2-a8b4-1c345a592f62)

And here is a test result. Notice multiple "github.com" tabs. None of which have changed to green, as per rule. 
![image](https://github.com/madprops/grasshopper/assets/32020577/9f387d9f-c496-4ba2-b2b8-4bae656cf553)


Worth noting that it **did** change, once. After I restarted the browser during testing. But then never again. 
Will update once it is available. As of this writing, last release was 16 hours ago. Will report back after I have updated.  
Cheers.

**Comment by daffydock** [comment]
LOL
Pushed update. It immediately started working. Will keep open for a little while just to double check everything is working. But it seems like you squashed it. 

As a side note, more of a question: Is there to increase the number of colours to pick? Than just four? If not, no worries. I am just curious if there is some setting that I may have missed. As a second question, have you thought of implementing an option for the bar to match the tab colour of the tab in question. Something akin to the  Adaptive Tab Colour Extention? 

https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-colour/

Yet I digress, as stated, I will keep the issue open but it seems like you fixed it. So I will close this a bit later, if you do not mind. Thanks.

**Comment by madprops** [comment]
Glad it works better now. 

>Is there to increase the number of colours to pick? 

Not at the moment. There's only 4 core colors. I might add an option to add more custom colors if those are not enough...

>an option for the bar to match the tab colour of the tab in question

The sounds interesting, but I think i'd have to inject some script in websites to check their css styles, and right now there's none of that happening. If firefox returned style data then it would be easy to implement.

At some point though there was a function to change the theme to the browser's theme if it could detect it, but it worked half the time.

**Comment by daffydock** [comment]
Okay, I tested in a number of ways, and with different test sites so far, it just works. 

As far as just the 4 colours. That is fine. No worries. It is a 'nice' to have but certainly not a must. 
As far as the second question, it is more for aesthetics and UX cohesiveness. In the end however, I lean on the nimble and a tight response. I played around with Sideberry, and it is a great add-on but somehow to me it feels sluggish unlike Grasshopper. 
  
I am all for keeping it lighter over just eye candy, specially if it only works about half of the time. Thanks for answering my questions. It is appreciated. 

I will close this. No need to keep it open longer than seemingly needed.

**Comment by daffydock** [comment]
Hi, 
Did you by any chance change anything since this issue was closed? The filters stopped working. Just noticed it.

**Comment by N3C2L** [comment]
I can confirm that. It is the color mode where only the icon setting works, but not the others.

**Comment by madprops** [comment]
Yeah I forgot to update some thing regarding colors. It should be working now.
