### ISSUE TITLE
reuse filter

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#79]
I think there is a bug when reuse filter is enabled. When typed into the search bar and then switching to filter red, the search bar is blank again.
Another observation:
If I am in an active filtering view, like color red, and then use the custom filter cmd: Shouldn't the custom filter be inserted in the search bar of the active filtering view (color red) instead of switching to "All" view and searching there?

**Comment by madprops** [comment]
Good observations. Both points are now fixed in `v2164`.

**Comment by N3C2L** [comment]
Thanks a lot! another small bug: ctrl+v does not work in the search bar.

**Comment by madprops** [comment]
Changed the filter context menu. It saves more filters now. Added Copy, Paste, and Clear.
Removed ctrl+c and ctrl+v shortcuts entirely so they can be used freely.

**Comment by N3C2L** [comment]
Thank you!
Just a little thing:
If the filter history is empty and you run the filter history cmd, there should be a popup informing that the filter history is empty. Else nothing appears when this cmd is executed.

**Comment by madprops** [comment]
Replaced the command with `Filter Context`

**Comment by N3C2L** [comment]
Sorry for reopening this issue, but:
The reuse filter does work with the buttons on top, but does not work if you switch the mode with the cmds "show history", "show bookmarks" and "show tabs".

**Comment by madprops** [comment]
I'll fix.
