### ISSUE TITLE
"All color" filter

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#8]
Hello again!

I want to organize my tabs in different colors and show them all in one applied filter.
I would be glad if you could implement a "All color" filter. If applied, the item list shows all tabs that have colors.

**Comment by N3C2L** [comment]
I was thinking "Filter Color" lists all colored tabs, but this is not working?

**Comment by madprops** [comment]
`Filter Color` is already another thing, what it does is filter by whatever color the item has. So if the item is green, it will filter green.

I'm adding filter by all colors functionality. This is accessed either through the filter menu by clicking All or via the command palette by using `Filter All  Colors`. 

Will upload soon.

**Comment by N3C2L** [comment]
Thank you very much for the explanations and the update.
