### ISSUE TITLE
Favorite button

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#84]
I found another bug.
How to reproduce:
1. Change the favorites mode to "button".
2. Add a random cmd in there.
3. Switch to the "playing" or "unloaded" view.
4. Click the favorites button.
5. Some cmds, for example the new added cmd, miss then there dependent on the selected view.

**Comment by madprops** [comment]
Commands are context aware. I think you added a command that doesn't meet some conditions. Do these views have items? Which command was it?

**Comment by N3C2L** [comment]
Oh, sorry. I didn't know that the cmds were content aware dependent on the view.
But it could maybe confuse people who switched the favorites mode from "bar" to "button" and then the cmds aren't visible when they click the favorites button on top.

**Comment by N3C2L** [comment]
There is a small bug in the duplicates filter view: the headers are listed there (even when they have other titles).

**Comment by madprops** [comment]
Duplicate bug fixed in next version. I'm gonna close this because for now I think unavailable commands shouldn't be shown, to avoid clutter.

**Comment by N3C2L** [comment]
I just want to add here another issue regarding the context awareness:
It is problematic for me when cmds button disappear in the favorites bar in the following case: I have mapped left click: color green, middle click: filter green. If I switch know to filter "Pins" this button disappear from the favorite bar. But this makes no sense because I have on the middle click the filter green mapped. So I could not filter green anymore. I would really have an option to disable the context awareness for the favorites bar.

**Comment by madprops** [comment]
Yeah I can see the issue .. i'll disable that by default.
