### ISSUE TITLE
Pins, Colors, Header

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#85]
I discovered some small bugs and would be pleased if you fix them:

1. If "hide pins" is checked, the pins are hidden in the Tab Box too.

2. I can't filter by color name: 

how to reproduce: 
2.1 activate "filter colors" in the filter settings
2.2 create a new color
2.3 give it a random name
2.4 search it

3. The Headers in the Tab Box have no background color. Edit: Apologies, I just realized that the color on the headers may be intentional to distinguish it from the button above, so it's not a bug.

**Comment by madprops** [comment]
Thanks, I appreciate these bug reports, as it can be hard to keep track of everything.

1) Fixed
2) Fixed
3) The headers in the tab box looked weird, I changed their style a bit.

Upload coming soon.

**Comment by N3C2L** [comment]
Thank you very much, everything is fine. I think I can close the issue.
