### ISSUE TITLE
Color changes

### ISSUE THREAD

**Issue by madprops** [madprops/grasshopper#86]
Colors can now be configured to appear in various modes.
The color settings didn't change but you'll have to re-enable them by selecting their mode since they default to "none".

This is about tab colors like "Active".

**Comment by N3C2L** [comment]
It's a bit confusing that you now get a different color. For example,
1. enable an active tab background color ("everywhere")
2. choose a color with the color picker (for example yellow)
3. switch to the Tab List, the color appears much darker there. 
4. But in the Tab Box it's the same color from the color picker.
I would prefer the same color that I colorpicked for the tab list as well.
This problem does not occur with other custom tab backgrounds (pins, unloaded etc.).

**Comment by madprops** [comment]
Yeah it's because they get the background effect since the item one is selected. But i'll change it to only affect if multiple tabs are selected

**Comment by madprops** [comment]
Ok this should be fixed.

**Comment by madprops** [comment]
I removed the 150ms transition. Also removed select_item on tab focus so further avoid pre-coloring the item.

**Comment by N3C2L** [comment]
Alright, thanks.

**Comment by madprops** [comment]
Uploaded some fixes. Let me know if it's better. I'm not sure I can get rid of the focus pre-color effect as I need to select items, but when I try it I can't notice the difference. I'm not sure what triggers the visual effect, maybe slow/busy cpu. But maybe it's better now, since no 150ms transition etc. `v2260`.

**Comment by N3C2L** [comment]
Thank you, I no longer notice any visual delay on the tab; everything looks as good as before. Thanks also for the hover fix, and the BG Contrast is set to 10 for me, which I find comfortable.

**Comment by madprops** [comment]
Great. I'm gonna move the contrast setting to General since it seems important.
