### ISSUE TITLE
Header pages are not pesistent

### ISSUE THREAD

**Issue by madprops** [madprops/grasshopper#87]
When the browser restarts, the moz-extension pages used for the headers change id, meaning their index.html content is no longer accesible.

I'm considering these options:

1) Use github pages to use a url that never changes, host the header files there, make headers point to that url.

2) Somehow find the new id and update the headers, but so far I haven't been able to find this id, maybe it's not possible

```
// All moz-extension URIs use a machine-specific UUID rather than the
// extension's own ID in the host component. This makes it more
// difficult for web pages to detect whether a user has a given add-on
// installed (by trying to load a moz-extension URI referring to a
// web_accessible_resource from the extension). getExtensionUUID
// returns the UUID for a given add-on ID.
```

3) Forget about header pages entirely, just use headers for organization, remove the activate mode.

I'm gonna wait for some feedback on this.

**Comment by madprops** [comment]
Ok I can get an updated URL by using `browser.extension.getURL("header/index.html")`

Maybe I can play with that. I'll check if it persists edits like color.

**Comment by N3C2L** [comment]
Glad that you found a solution. Option 2 is important for me, because I rely on the activate mode of the headers cause of Floorp.
