### ISSUE TITLE
icons, tab box, taglist

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#88]
I found some bugs and would be glad if you fix them:

1. The icons filtering doesn't work.

2. Under settings > tab box mode > tags and icons are missing.

3. I have a small issue with the taglist and would appreciate it if you could take a look. I have set the taglist to "Below". When a tag is added, the entire tab item height increases. However, in the area to the right of the tag, you can no longer activate the tab. Would it be possible for the tab to be activated when clicking in the free space to the right of the tag? It's the same issue when the taglist is set to "Above".

4. Currently, Header Tabs are not unloaded when clicking "unload" cmd on the header tab. I have noticed that Tabs with an internal URLs cannot be unloaded. Perhaps it would be different if the header URL pointing on GitHub? It would be beneficial for filtering if the Header Tab could be unloaded and loaded. This way, the Header Tabs could be filtered separately in unloaded and loaded views. The "Header Action" must set to "activate" in the zones settings for getting a Header in the loaded state.

**Comment by madprops** [comment]
1) Fixed. Oops
2) Fixed. Forgot that
3) Fixed. Now only the container area catches the clicks instead of the whole taglist.
4) They can unload now. I manually disabled that since they were special tabs, but they can be unloaded now.

Thanks.

**Comment by N3C2L** [comment]
Thanks a bunch!

Also, 2 more things:

1. The moz-extension html page of the header doesn't save the color. This means that when a new header is created, it loads the default black color again and not the previously saved one in the html page.

2. Now that the user can decide whether to set header tabs as unloaded/loaded, it would be good if the header tabs could be displayed again in the "Loaded" view. Because in the "Unloaded" view, the header tabs are visible again if they have been manually unloaded.

**Comment by madprops** [comment]
1) Sure i'll bring that back

2) Ok makes sense

Also adding a command to close all zones (headers, subheaders, splits).

**Comment by N3C2L** [comment]
Thank you! And this new cmd is convenient. You resolved all issues, thanks. I think I can close this.
