### ISSUE TITLE
Filter seems to inconsistently erase/reset

### ISSUE THREAD

**Issue by fireworksordie** [madprops/grasshopper#9]
I'm not sure if this is a setting or the result of an update or because i have way too many tabs open (2550, way too many, but RAM usage overall isn't too wild relative to what I have available), but after typing in a filter it will disappear after 5 to 10 seconds. But also sometimes it doesn't for a while. Anything I can do to better troubleshoot this?

**Comment by madprops** [comment]
There's an "auto-restore" setting in General Settings. Maybe it's that. When the mouse leaves the window it will auto-restore after some seconds, including clearing the filter. You can disable that by setting it to never. Maybe I should set the default to never.

**Comment by madprops** [comment]
>But also sometimes it doesn't for a while
Not sure what that could be...

**Comment by fireworksordie** [comment]
> There's an "auto-restore" setting in General Settings. Maybe it's that. When the mouse leaves the window it will auto-restore after some seconds, including clearing the filter. You can disable that by setting it to never. Maybe I should set the default to never.

Almost certainly this, thanks for pointing that out! I was looking under the Filter settings to no avail. And yeah - from a user experience perspective I think it would be best set to never. In my use case just a moment ago I was referring back and forth between the sidebar and content in the window and I was super confused
