### ISSUE TITLE
Floorp Sidebar

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#91]
I have a specific issue: When using Floorp with two Grasshopper instances loaded (two sidebars; left and right), they are mostly in sync. This means that if, for example, an icon/color/tag is added or replaced on one tab, this change is also reflected in the other Grasshopper. That's perfect, and I like it that way. However, when an icon/color/tag is removed from the tab, this change is not registered in the other Grasshopper, so the Grasshoppers are not synchronized in this case. For instance, if you click the middle mouse button on an icon/color/tag to remove it from the tab. It would be really great if you could take a look at this.

You could reproduce this by installing Grasshopper in Floorp. In the Floorp settings, you can activate the second Floorp sidebar by searching for "Browser Manager Sidebar" in the options and setting it on the right side of Firefox, so that the native Firefox sidebar is on the left and the Floorp sidebar is on the right.

Then click on the "+" symbol
<img width="26" alt="floorp sidebar" src="https://github.com/madprops/grasshopper/assets/74585843/334995ad-4e3c-4ff6-9a9b-a058d4f91ec3">

and select Grasshopper from the list.

**Comment by N3C2L** [comment]
I wanted to mention that the filter views and the tab box sections should not synchronize, as this allows for different views in both Grasshopper instances.

**Comment by madprops** [comment]
It should be fixed now

**Comment by N3C2L** [comment]
Thanks, very good. I think I can close this.

**Comment by madprops** [comment]
I'll just make it a setting

**Comment by N3C2L** [comment]
Thanks, I think it's useful for some users who don't use 2 sidebars but do use the popup and the sidebar rotatory. But I don't need this Mirror feature. When it's activated, the Tab Box in both sidebars is synchronized, so different views of Tab Boxes can't be displayed in each sidebar. Instead, it always shows the same view. Also, I have set the Favorites Bar vertically in one sidebar and at the bottom in the other sidebar. This wouldn't work with Mirror Settings because both Favorites Bars would always be in the same position (for example, both vertical or both at the bottom).
