### ISSUE TITLE
media

### ISSUE THREAD

**Issue by N3C2L** [madprops/grasshopper#93]
When I open a file, for example, jpeg/mp3, in a tab and then click on the image icon (audio/video/images icon), only "error" appears in the tab.

Observation:
People might think that "Media" is filtering website URLs. For example, if you filter videos, all URLs from video sites like Youtube or Vimeo would be displayed. Similarly, if people filter images, they might think it lists all tabs related to image sites like Pinterest or Instagram.  

It should be clarified in the description of "Media" that only files on the hard drive are filtered here and not website URLs related to audio/video/images.

Once the feature freeze is over in the next few days, do you think it would be possible to have an option that is something like an "Url Filter"? For example, if one enters "images" in the text input field, all URLs that have been entered under "images" would be listed (similar to an alias, but with aliases, you can only enter words, not URLs, and not multiple words per alias).

**Comment by madprops** [comment]
Can you give me some url examples where it errors out? All it does is try to load <img> or <audio> or <video>

**Comment by N3C2L** [comment]
The error occurs on every file I drag and drop from my hard drive into the browser. And then clicking on the media icon next to the generated favicon. The media should be displayed in the grasshopper interface, right?

**Comment by madprops** [comment]
Yeah. I don't know why firefox disallows loading local files, but it's a restriction it imposes

**Comment by N3C2L** [comment]
Okay, yes, for security reasons, that would be understandable from Firefox's perspective. Well, then it works and is not a bug.

**Comment by N3C2L** [comment]
Ok, thanks.

**Comment by madprops** [comment]
Aliases work for urls if you don't include the protocol (like https://)

**Comment by N3C2L** [comment]
Okay, thank you. But what would a feature be called where multiple words are searched with a single search term? For example, the search term 'Video.' Here, all video sites would be displayed, like Youtube or Vimeo, etc.

**Comment by madprops** [comment]
You can add a domain rule to each of those sites to have a tag "vidz" for example

![vidz](https://github.com/madprops/grasshopper/assets/206498/52117ea8-fa50-4dd7-89a7-4b2e5077d45d)

**Comment by N3C2L** [comment]
Ok, that would work, thanks.
Hmm. But I have tags visible on other tabs and don't want to have them visible also on youtube tabs or similar video tabs. Do you think there could be a blacklist for tab urls where tags shouldn't appear then?

**Comment by madprops** [comment]
You mean the taglist?

**Comment by N3C2L** [comment]
Yes, an option to hide the tag in the taglist, maybe a setting in the domain rule. Because I have set the taglist to "Below" and always visible.

**Comment by madprops** [comment]
No plans for that at the moment.

**Comment by N3C2L** [comment]
Ok, thanks.
I think I am going with a video icon then. A Domain rule where every video gets the video icon. And then filtering the icon only, that displays all video urls.

**Comment by madprops** [comment]
That's an idea. There's also making regex Custom Filters like:

```
re_url: youtube.com|vimeo.com
```

**Comment by N3C2L** [comment]
Ah, that's helpful. With that, you can also showcase multiple pages without domain rules.

**Comment by madprops** [comment]
The tabs filter now supports using | 
| was removed before, but it's now alloed
This means that it can be considered in the filter regex
So you can type youtube|vimeo
And you can use this in the Aliases setting

**Comment by N3C2L** [comment]
This is fascinating!
So now I can filter multiple URLs with a search term as an alias. Thanks!
And the fact that you don't need domain extensions is practical.
