### ISSUE TITLE
Keyboard scroll moving only 9 tabs height up/down.

### ISSUE THREAD

**Issue by user0022** [madprops/grasshopper#95]
Hello!
Just for my first post here, thanks for your addon! I use it since 1 week and I think it can absolutly become my new tab manager.
MANY useful options, while apparently staying light on resources (I'm no developper at all but I wonder how you achieve that).
Even features I had imagined myself years ago, hoping that one day I could ask an addon developper to built it, I had even tinkered some for myself (or tried so, with my poor HTML+CSS): separations between tab scopes with titles on them, marks on tabs according to important/good/average/bad/etc. But now it's all done.

I use FF ESR for the moment (115.10), under Lubuntu 22.04 OS.
And in my posts I always talk about sidebar view, as I always use this view as it can display more tabs.

To describe a bit my case, which may help to understand better my questions, I will say that I'm a bit of a "tab hoarder"/tabcoholic, currently with (only) 5000 tabs in Firefox, so an important goal is to find a tab among others with not too much time losing (and also other management options).

I've tried several addons to help me in that, but not all of them.
The wonderful [Tab Mix Plus](github.com/onemen/TabMixPlus) (esp. for multiline) was back (with a third party software for legacy addons) but there had been a bug and FF refused it (perhaps now solved idk), [All Tabs Helper](addons.mozilla.org/en-US/firefox/addon/all-tabs-helper/) seems (or seemed) the best for me but isn't maintained anymore. [Tab Center Reborn](addons.mozilla.org/en-US/firefox/addon/tabcenter-reborn/) was maybe good for me but its pages show some evil personnal ideology ahem (easier to see in french), anyway last update is 3 years ago. Today I installed [Sidebery](addons.mozilla.org/fr/firefox/addon/sidebery/), it seems good, and maybe that I should have installed long ago. Etc.

*

So would have some questions/suggestions, I post some today, I saw [in another issue](github.com/madprops/grasshopper/issues/94) that new features is frozen for the moment? No problem, I could post "feature requests" later but after all if I post them that doesn't mean I'm in a hurry and I will suicide, if accepted it can be in 1 month or 1 year. Thank you anyway.

*

(So, about the issue!!)
In sidebar, instead of showing all of the next/previous new ones, only 9 next/previous come.
I use my laptop keyboard, which usually works in any software interface. Then the up and down keys (to the right of the [Enter] key) show "screen by screen".

If it has an importance, I had modified some values to shrink tabs height (I can indicate them if asked), to display more tabs at the time, default sidebar showed me 14, now I can see 35.

**Comment by madprops** [comment]
Hi.

Sorry I don't understand this part

`In sidebar, instead of showing all of the next/previous new ones, only 9 next/previous come.`

What are you talking about? Scroll moves by 9 items? When doing what

I don't understand the problem

You only see 9 items?

**Comment by user0022** [comment]
Thanks for fast answer!

Well I think it's very simple, but maybe I don't explain very well excuse-me, as a french-speaker my english is not on top.

It is like in a web page, or in a text editor, say I have 200 lines of text.
If I'm on the top of the page, and I see say the 50 first lines, if I scroll down with a click on the down key (on the right of the [Enter] key), I will see lines from 50 to 100 (the next ones), a second click and I see lines from 100 to 150, a click on up key and I see again lines from 50 to 100 (now the previous ones), etc. We can call it "screen by screen" up/down moving (maybe there's a more correct name).
So if I replace the text editor with the sidebar, and the lines with the tabs, it is supposed to be the same (like ATH addon did, and other sidebar addons I tried, if I remember well). But with the down arrow I see only the 9 next ones (of course all the other ones don't disappear, I still see 50 tabs (35 in my real sidebar, 50 is to stick with the example), but the 9 "previous" on the top disappear, and I see the 9 next ones on the bottom, like a rolling.
So the move (the next/previous tabs display), the "rolling", is only partial instead of being total, with a total I should see the 50 next tabs (like the 50 next lines in the editor).

Hope I've been clearer.

**Comment by madprops** [comment]
`The term for full page scrolling is "Page Navigation". When you press the PageDown key, it moves the view of the page down by one screen. Similarly, the PageUp key moves the view of the page up by one screen. This allows you to navigate through your document or webpage a full screen at a time, which can be faster and more efficient than scrolling line by line.`

I think this is what you mean.

I can change the behavior of PageUp and PageDown to do this. But not the up/down arrows, those should move one item at a time as they do.

Would that be good enough for you, using the PageUp and PageDown buttons?

**Comment by user0022** [comment]
OK, that's it yes. I didn't know (or remembered enough) the names for each, Up and PageUp.

I just went in my Keyboard "software", thinking maybe there was a problem of bad recognition of my keys. Visibly to show my laptop keyboard they show a desktop keyboard, which I find strange, but in fact it must be a wrong idea, for if it were the case, a priori the problem would appear also in a browser or a text editor.

So now I think I know the names, I can say that my Up and Down keys work well (not the PageUP and PageDown keys, that by error I had called Up and Down). PageUp and PageDown are like I said (with wrong name) to the right of the [Enter] key (and on their right there are not keys anymore), and Up and Down keys are on the bottom on the right of the keyboard. And these Up/Down work well, they move one item at the time. So yes if the PageUp and PageDown could work as I hope, it would be great, so I repeat that I used the wrong name, Up/Down are OK, it's PageUp and PageDown which do only partial scrollings. 
But if this is set/fixed, was it only me (or some cases) or general, if I may ask.

**Comment by madprops** [comment]
I changed the behavior of PageUp and PageDown, now they do full page scrolls. 

Also added a setting to disable it (it's  enabled by default) in More, called `Page Scrolls`.

**Comment by madprops** [comment]
A yeah. I think I know what the problem might be. I'll see if I can fix it.

**Comment by user0022** [comment]
I've never tried gestures on my laptop, maybe I wiil, but to go to the top/bottom, a click maintained on the scrollbar and a move to the top/bottom is OK to me I think, the problem is rather going back to the tab I was before, that is not too long neither, with a click on Show Recent in Favorites (and even afterwards scrolling a bit up or down to have the same view on surrounding tabs if necessary). I think I can live with these few clicks.

I could close the issue I guess, but maybe also you would one day want to make the pins sticky so it is not "Close"? So I leave it up to you!

**Comment by user0022** [comment]
OK for the focus issue, I would have been yet sure that it worked differently before, so I remembered bad!

**Comment by madprops** [comment]
On the new version this should be fixed.

**Comment by user0022** [comment]
Thank you I confirm it now work perfectly!
