### ISSUE TITLE
Keep pinned tabs pinned.

### ISSUE THREAD

**Issue by user0022** [madprops/grasshopper#96]
Hello!
I use Firefox ESR 115, under Lubuntu 22.04 OS.

*

As fas as I could see, pinned tabs have some features, but they are not sticky, like in the FF tab bar, and like in fact they're should be I guess as "pinned". I don't know if it is a bug or a Firefox limitation or voluntary, but could they be sticky?
If they take too much space, as sticky things reduce the place for the rest, they could maybe optionnally move like other tabs (like for now), or be foldable or else.

**Comment by madprops** [comment]
They are not sticky indeed.

A workaround is using the pins icon on the sidebar (of the sidebar, on the left) to access the pins. Or filter them, there are various ways

**Comment by user0022** [comment]
Thanks for answer!
Yes I didn't try other ways, the pins icon seems a good alternative why not.

Unfortunately, real sticky tabs would be still faster to access, 1 movement + 1 click.
The pins icon will be 1 movement + 1 click + 1 movement + 1 click, and probably no other alternative would do better.

Personnally I think I can use this icon OK. Hoping that for other people it would not be a more bothering thing.

**Comment by madprops** [comment]
Something I do myself often is use the mouse gestures to go to the top. I click and hold the middle mouse button and move upwards to go back to the top (or bottom). This is very easy with a mouse, maybe not on laptop.

**Comment by user0022** [comment]
I've never tried gestures on my laptop, maybe I wiil, but to go to the top/bottom, a click maintained on the scrollbar and a move to the top/bottom is OK to me I think, the problem is rather going back to the tab I was before, that is not too long neither, with a click on Show Recent in Favorites (and even afterwards scrolling a bit up or down to have the same view on surrounding tabs if necessary). I think I can live with these few clicks.

I could close the issue I guess, but maybe also you would one day want to make the pins sticky so it is not "Close"? So I leave it up to you!

**Comment by madprops** [comment]
Try the Tab Box, on the bottom left corner. I think it does exactly what you need. If you click it's header/title you can change it to Pins mode. If you right click that header you can change its position, move it to the top, etc.

**Comment by madprops** [comment]
![tabbox234](https://github.com/madprops/grasshopper/assets/206498/b94926a8-c600-492f-b53f-4a8a9b3d48db)

**Comment by madprops** [comment]
![tabbbox892348](https://github.com/madprops/grasshopper/assets/206498/9fdc60d6-3ce9-455f-8ed0-aaf9c102cc05)

**Comment by user0022** [comment]
I did it, yes it seems to work well!
I check a bit more...

**Comment by user0022** [comment]
Yes it is not bad, finally this way almost real Pins.

And also to not show them twice for nothing, one will do:
`Settings` > `Show` > Check: `[x] Hide Pins`.

Now I can't use Tab Box for something else but I probably wouldn't have so it is not a problem.

Just remains a feature of space saving, as they are sticky and space they take is always taken. Firefox allows them to show only icons, and e.g. in [Sidebery](addons.mozilla.org/en-US/firefox/addon/sidebery/) addon they can also, and plus being displayed side by side instead of one's line under the other (like can be seen in n° 1 and 3 out of its 5 screenshots in his addon page), this way several can take only 1 line.
To save space, a possibility is of course to do in Tab Box settings:
`Tab Box Size`: `[Tiny]`.
`Tab Box Auto Grow`: Put `[None]` to something else.
(If I didn't miss something.)

But Sidebery's way is better I would say, whith 10+ pins . Maybe you would do the same thing one day?
For the moment, as personnally I don't have 10 pins in a sidebar, they don't take too much space even without `Tab Box Auto Grow` etc, so for me thank you it's OK.
