### ISSUE TITLE
[BUG] Header/subheader background color not modified.

### ISSUE THREAD

**Issue by user0022** [madprops/grasshopper#97]
Hello!
I use Firefox ESR 115, under Lubuntu 22.04 OS.

*

In `Settings` > `Zones`, I modified those 2 colors, but it wasn't taken into account.
I tried 1 or 2 little things:
-Close/reopen the Sidebar;
-Open the Popup;
-Create a new Header;
-Change the `[Everywhere] `option to `[Normal]`.
But nothing changed...

If it can have an importance, I had already changed some background colors, general background maybe (background image removed), and tabs also (active, loaded, unloaded, but I don't remember exactly).

**Comment by madprops** [comment]
Does seem to be a problem. I'm checking it out.

**Comment by madprops** [comment]
The colors were not being applied to header and subheader. I added these to a list that forces the colors to be applied. Should work in next version.

**Comment by user0022** [comment]
Thanks, now I'll see them from far! :)
But I'm not sure to understand
"Also for these to take effect, the mode has to be set to Normal or Everywhere on each item."
Means if I change the color for Headers set to [Normal], the subheaders have to be also set to [Normal], and this with or without color modification?
If it is so, I guess you will write it besides, for the user to know it, or will force the other one to set automatically to the same option as the first one (or something of this kind).
But maybe I didn't understand?
(I must go, I'll see probably the following tomorrow).

**Comment by madprops** [comment]
![headerbg](https://github.com/madprops/grasshopper/assets/206498/a2f3dcda-0393-4626-a30e-e9f2f78a61c6)

It simply controls where to apply the effect.

Normal = tabs, normally (this is what you want probably)

Tab Box = only on the tab box

Everywhere = on both

**Comment by user0022** [comment]
It worked thank you!
It's really better this way, before, headers were not very recognizable when scrolling just a bit too fast.

For what I didn't understand, I think I see, it was nothing special I has imagined, "on each item" simply meaning both (but individually) must be set to `[Normal]` or `[Ewerywhere]`.

I think I can close!
