### ISSUE TITLE
[BUG] Pinline always shows despite setting.

### ISSUE THREAD

**Issue by user0022** [madprops/grasshopper#98]
Hello!
I use Firefox ESR 115, under Lubuntu 22.04 OS.

*

In `Settings` > `Show`, I put `Show Pinline` to `[Never]`, but it still always displays.
This in Sidebar as well as in Popup, and with pinned tabs or with not.
Right below, I had put `Close Button` to `[None]` and it worked (so it is not that the settings of this category are boken for me).

**Comment by madprops** [comment]
Seems that is happening. I'll check it out.

**Comment by madprops** [comment]
There was indeed no proper check for `never`. Next version should have this fixed. Which I will upload in 30mins or so.

**Comment by user0022** [comment]
Thanks and congratulations for fast fix!
